/**
 * @file main.c
 * @brief AkiraOS SMS emulator — app entry point
 *
 * Reads SMS buttons from the akiraconsole DPAD GPIOs, runs the SMS
 * machine, and pushes each frame to the AkiraOS display via
 * display_bitmap().  The SMS 256×192 image is centered on the
 * 320×240 display with 32-pixel black bars on left/right and 24-pixel
 * bars on top/bottom.
 *
 * ROM data is supplied by rom_data.c (generated by rom_to_wasm.py):
 *   const uint8_t  rom_data[];
 *   const uint32_t rom_size;
 *
 * Button mapping (akiraconsole pins):
 *   D-pad Up    (pin  4) → SMS Up
 *   D-pad Down  (pin  5) → SMS Down
 *   D-pad Left  (pin  6) → SMS Left
 *   D-pad Right (pin  7) → SMS Right
 *   A button    (pin 15) → SMS Button 1
 *   B button    (pin 16) → SMS Button 2
 *   Y button    (pin 41) → SMS Start / Pause (NMI)
 *   Settings    (pin  2) → Emulator pause menu
 *
 * @license Apache-2.0
 */
#include "akira_api.h"
#include "sms.h"

/* ── ROM data (generated by rom_to_wasm.py) ─────────────────────────── */
extern const uint8_t  rom_data[];
extern const uint32_t rom_size;

/* ── Display geometry ────────────────────────────────────────────────── */
#define DISP_W        320
#define DISP_H        240
#define SMS_OFFSET_X  ((DISP_W - SMS_W) / 2)   /* 32 px left margin  */
#define SMS_OFFSET_Y  ((DISP_H - SMS_H) / 2)   /* 24 px top margin   */

/* ── Overscan ─────────────────────────────────────────────────────────── */
#define SMS_OVERSCAN      8
#define SMS_CROP_H        (SMS_H - 2 * SMS_OVERSCAN)   /* 176 px */
#define SMS_CROP_OFFSET_Y ((DISP_H - SMS_CROP_H) / 2)  /* 32 px  */

/* ── Frameskip ───────────────────────────────────────────────────────── */
static const int FS_MOD[4] = {1, 2, 3, 4};  /* 60 / 30 / 20 / 15 fps */
static int g_frameskip = 1;                  /* default: 30 fps */
static int g_overscan  = 0;                  /* default: off    */

/* ── GPIO pin assignments ────────────────────────────────────────────── */
#define PIN_UP        4
#define PIN_DOWN      5
#define PIN_LEFT      6
#define PIN_RIGHT     7
#define PIN_A        15
#define PIN_B        16
#define PIN_X        17
#define PIN_Y        41
#define PIN_SETTINGS  0

/* ── Colours (RGB565) ────────────────────────────────────────────────── */
#define C_BLACK   0x0000u
#define C_WHITE   0xFFFFu
#define C_LGRAY   0xC618u
#define C_DGRAY   0x4208u
#define C_DIM     0x528Au

/* ── UI layout ────────────────────────────────────────────────────────── */
#define ROW_H     26
#define MENU_PAD  10
#define HDR_H     22

/* ── Pause menu ──────────────────────────────────────────────────────── */
#define MENU_RESUME   0
#define MENU_SETTINGS 1
#define MENU_RESTART  2
#define MENU_EXIT     3
#define MENU_COUNT    4

static const char *MENU_LABELS[MENU_COUNT] = {
    "Resume", "Settings...", "Restart", "Exit to Menu"
};

/* ── Tiny string helpers ─────────────────────────────────────────────── */
static int satoi(const char *s)
{
    int v = 0;
    while (*s >= '0' && *s <= '9') v = v * 10 + (*s++ - '0');
    return v;
}
static void sitoa(int v, char *b, int max)
{
    if (v == 0) { b[0]='0'; b[1]='\0'; return; }
    char t[8]; int ti=0, i=0;
    while (v>0 && ti<7) { t[ti++]='0'+v%10; v/=10; }
    while (ti-->0 && i<max-1) b[i++]=t[ti];
    b[i]='\0';
}

/* ── Settings persistence ────────────────────────────────────────────── */
static void load_settings(void)
{
    char buf[8];
    if (settings_get("sms/frameskip", buf, sizeof(buf)) == 0) {
        g_frameskip = satoi(buf);
        if (g_frameskip < 0) g_frameskip = 0;
        if (g_frameskip > 3) g_frameskip = 3;
    }
    if (settings_get("sms/overscan", buf, sizeof(buf)) == 0)
        g_overscan = satoi(buf) ? 1 : 0;
}
static void save_int(const char *key, int val)
{
    char buf[8];
    sitoa(val, buf, sizeof(buf));
    settings_set(key, buf);
}

/* ── Border bars ─────────────────────────────────────────────────────────── */
static void draw_border(void)
{
    int img_y = g_overscan ? SMS_CROP_OFFSET_Y : SMS_OFFSET_Y;
    int img_h = g_overscan ? SMS_CROP_H        : SMS_H;
    display_rect(0,                    0, SMS_OFFSET_X,              DISP_H, 0x0000);
    display_rect(SMS_OFFSET_X + SMS_W, 0, SMS_OFFSET_X,              DISP_H, 0x0000);
    display_rect(0,                    0, DISP_W,              img_y,        0x0000);
    display_rect(0,           img_y + img_h, DISP_W, DISP_H - img_y - img_h, 0x0000);
}

/* ── Draw helpers ─────────────────────────────────────────────────────── */
static void draw_header(int x, int y, int w, const char *title)
{
    display_rect(x, y, w, HDR_H, C_BLACK);
    display_text(x + MENU_PAD, y + 4, title, C_WHITE);
}

static void draw_row(int x, int y, int w,
                     const char *lbl, const char *val, int sel)
{
    uint16_t bg = sel ? C_BLACK : C_WHITE;
    uint16_t fg = sel ? C_WHITE : C_BLACK;
    display_rect(x, y, w, ROW_H, bg);
    display_text(x + MENU_PAD, y + (ROW_H - 8) / 2, lbl, fg);
    if (val && val[0]) {
        int vx = x + w - 60;
        if (vx > x + 80)
            display_text(vx, y + (ROW_H - 8) / 2, val, sel ? C_LGRAY : C_DIM);
    }
    display_hline(x, y + ROW_H - 1, w, C_LGRAY);
}

/* ── Settings sub-menu ────────────────────────────────────────────────── */
static void show_settings_menu(void)
{
    static const char *FS_LABELS[4] = {
        "Off (60fps)", "Half (30fps)", "1/3 (20fps)", "1/4 (15fps)"
    };
    const int OW = 180;
    const int OH = HDR_H + 3 * ROW_H;  /* Frameskip + Overscan + Back */
    const int OX = (DISP_W - OW) / 2, OY = (DISP_H - OH) / 2;

    int cur=0, dirty=1;
    int pu=0, pd=0, pa=0, pb=0, pl=0, pr=0;

    while (1) {
        if (dirty) {
            display_rect(OX-2, OY-2, OW+4, OH+4, C_DGRAY);
            display_rect(OX,   OY,   OW,   OH,   C_WHITE);
            draw_header(OX, OY, OW, "Settings");
            int ry = OY + HDR_H;
            draw_row(OX, ry, OW, "Frame Skip", FS_LABELS[g_frameskip], cur==0); ry += ROW_H;
            draw_row(OX, ry, OW, "Overscan",   g_overscan?"On":"Off",  cur==1); ry += ROW_H;
            draw_row(OX, ry, OW, "Back",       "",                     cur==2);
            display_flush();
            dirty = 0;
        }
        int u=gpio_read(PIN_UP), d=gpio_read(PIN_DOWN);
        int a=gpio_read(PIN_A),  b=gpio_read(PIN_B);
        int l=gpio_read(PIN_LEFT),r=gpio_read(PIN_RIGHT);

        if (u&&!pu) { cur=(cur+2)%3; dirty=1; }
        if (d&&!pd) { cur=(cur+1)%3; dirty=1; }
        if ((l&&!pl)||(r&&!pr)) {
            int delta = (r&&!pr) ? 1 : -1;
            if (cur==0) { g_frameskip=(g_frameskip+delta+4)%4; save_int("sms/frameskip",g_frameskip); dirty=1; }
            if (cur==1) { g_overscan^=1; save_int("sms/overscan",g_overscan); dirty=1; }
        }
        if (a&&!pa) {
            if (cur==0) { g_frameskip=(g_frameskip+1)%4; save_int("sms/frameskip",g_frameskip); dirty=1; }
            else if (cur==1) { g_overscan^=1; save_int("sms/overscan",g_overscan); dirty=1; }
            else break;
        }
        if (b&&!pb) break;
        pu=u; pd=d; pa=a; pb=b; pl=l; pr=r;
        delay(20000);
    }
}

static int show_pause_menu(void)
{
    /* Wait for Settings button release */
    while (gpio_read(PIN_SETTINGS)) delay(10000);
    delay(40000);

    const int OW = 170;
    const int OH = HDR_H + MENU_COUNT * ROW_H;
    const int OX = (DISP_W - OW) / 2, OY = (DISP_H - OH) / 2;

    int cur=0, dirty=1;
    int pu=0, pd=0, pa=0, pb=0, ps=0;

    while (1) {
        if (dirty) {
            /* Slide-in effect: draw overlay from left edge */
            for (int x = OX - 20; x <= OX; x += 8) {
                int cx = x < OX ? x : OX;
                display_rect(cx-2, OY-2, OW+4, OH+4, C_DGRAY);
                display_rect(cx,   OY,   OW,   OH,   C_WHITE);
                draw_header(cx, OY, OW, "PAUSED");
                int ry = OY + HDR_H;
                for (int i = 0; i < MENU_COUNT; i++) {
                    draw_row(cx, ry, OW, MENU_LABELS[i], "", i==cur);
                    ry += ROW_H;
                }
                display_flush();
                delay(8000);
            }
            dirty = 0;
        }
        int s=gpio_read(PIN_SETTINGS);
        int u=gpio_read(PIN_UP), d=gpio_read(PIN_DOWN);
        int a=gpio_read(PIN_A),  b=gpio_read(PIN_B);

        if (s&&!ps) return MENU_RESUME;
        if (u&&!pu) { cur=(cur+MENU_COUNT-1)%MENU_COUNT; dirty=1; }
        if (d&&!pd) { cur=(cur+1)%MENU_COUNT;             dirty=1; }
        if (a&&!pa) {
            if (cur==MENU_SETTINGS) { show_settings_menu(); dirty=1; continue; }
            return cur;
        }
        if (b&&!pb) return MENU_RESUME;
        pu=u; pd=d; pa=a; pb=b; ps=s;
        delay(16667);
    }
}

/* ── GPIO setup ──────────────────────────────────────────────────────── */
static void init_gpio(void)
{
    int flags = GPIO_INPUT | GPIO_PULL_UP | GPIO_ACTIVE_LOW;
    gpio_configure(PIN_UP,       flags);
    gpio_configure(PIN_DOWN,     flags);
    gpio_configure(PIN_LEFT,     flags);
    gpio_configure(PIN_RIGHT,    flags);
    gpio_configure(PIN_A,        flags);
    gpio_configure(PIN_B,        flags);
    gpio_configure(PIN_X,        flags);
    gpio_configure(PIN_Y,        flags);
    gpio_configure(PIN_SETTINGS, flags);
}

/* ── SMS machine (static: avoids stack overflow) ─────────────────────── */
static SMS sms;

/* ── Main ────────────────────────────────────────────────────────────── */
int main(void)
{
    printf("AkiraOS SMS Emulator\n");

    init_gpio();
    load_settings();

    display_clear(0x0000);
    display_text_large(60, 100, "SMS", 0xFFFF);
    display_text_large(120, 100, "EMULATOR", 0xFFFF);
    display_text(90, 140, "Loading ROM...", 0xFFFF);
    display_flush();

    if (sms_init(&sms, rom_data, rom_size) != 0) {
        display_clear(0x0000);
        display_text(40, 110, "ERROR: ROM init failed", 0xF800);
        display_flush();
        delay(4000000);
        app_switch("supervisor");
        return 1;
    }

    draw_border();
    display_flush();

    int prev_settings = 0;
    int frame_count   = 0;

    printf("[SMS] Init OK — entering main loop\n");

    while (1) {
        int settings_now = gpio_read(PIN_SETTINGS);

        /* ── Read input: Y=START/NMI ─────────────────────────────────── */
        uint8_t btns = 0;
        if (gpio_read(PIN_UP))    btns |= SMS_BTN_UP;
        if (gpio_read(PIN_DOWN))  btns |= SMS_BTN_DOWN;
        if (gpio_read(PIN_LEFT))  btns |= SMS_BTN_LEFT;
        if (gpio_read(PIN_RIGHT)) btns |= SMS_BTN_RIGHT;
        if (gpio_read(PIN_A))     btns |= SMS_BTN_1;
        if (gpio_read(PIN_B))     btns |= SMS_BTN_2;
        if (gpio_read(PIN_Y))     btns |= SMS_BTN_START;

        sms_set_buttons(&sms, 0, btns);

        /* ── SETTINGS rising edge → emulator pause ───────────────────── */
        if (settings_now && !prev_settings) {
            int choice = show_pause_menu();
            if (choice == MENU_EXIT) {
                app_switch("supervisor");
                return 0;
            }
            if (choice == MENU_RESTART) {
                sms_init(&sms, rom_data, rom_size);
                draw_border();
                display_flush();
                frame_count = 0;
                printf("[SMS] Restarted\n");
            }
        }
        prev_settings = settings_now;

        /* ── Run one SMS frame + optional render skip ────────────────── */
        int mod  = FS_MOD[g_frameskip];
        int skip = (frame_count % mod) != 0;
        sms.vdp.skip_render = (uint8_t)skip;
        sms_step_frame(&sms);
        frame_count++;

        /* ── Display ──────────────────────────────────────────────────── */
        if (!skip) {
            if (g_overscan) {
                display_bitmap(SMS_OFFSET_X, SMS_CROP_OFFSET_Y,
                               SMS_W, SMS_CROP_H,
                               (uint8_t *)sms.fb + SMS_W * SMS_OVERSCAN * 2,
                               SMS_W * SMS_CROP_H * 2);
            } else {
                display_bitmap(SMS_OFFSET_X, SMS_OFFSET_Y,
                               SMS_W, SMS_H,
                               sms.fb, SMS_FB_BYTES);
            }
            display_flush();
        }
    }

    return 0;
}
