/**
 * @file main.c
 * @brief AkiraOS SMS emulator — app entry point
 *
 * Reads SMS buttons via input_get_buttons(), runs the SMS
 * machine, and pushes each frame to the AkiraOS display via
 * display_bitmap().  The SMS 256×192 image is centered on the
 * 320×240 display with 32-pixel black bars on left/right and 24-pixel
 * bars on top/bottom.
 *
 * ROM data is supplied by rom_data.c (generated by rom_to_wasm.py):
 *   const uint8_t  rom_data[];
 *   const uint32_t rom_size;
 *
 * Button mapping (via input_get_buttons(), kernel gpio-keys):
 *   D-pad Up/Down/Left/Right → SMS Up/Down/Left/Right
 *   A button    → SMS Button 1
 *   physical Y  → SMS Button 2
 *   physical X  → SMS Start / Pause (NMI)
 *   Home/OK     → Emulator pause menu
 *
 * @license Apache-2.0
 */
#include "akira_api.h"
#include "sms.h"
#include "save_state.h"

#define SAVE_SLOT_COUNT 3
static const char *save_slot_path(int slot)
{
    static const char *PATHS[SAVE_SLOT_COUNT] = { "save1.bin", "save2.bin", "save3.bin" };
    return PATHS[slot];
}

/* ── ROM data (generated by rom_to_wasm.py) ─────────────────────────── */
extern const uint8_t  rom_data[];
extern const uint32_t rom_size;

/* ── Display geometry (queried at startup — see init_display_geometry) ─── */
static int g_disp_w, g_disp_h;
static int g_sms_dst_x, g_sms_dst_y;        /* centred position, no overscan */

/* ── Overscan ─────────────────────────────────────────────────────────── */
#define SMS_OVERSCAN      8
#define SMS_CROP_H        (SMS_H - 2 * SMS_OVERSCAN)   /* 176 px */
static int g_sms_crop_dst_y;                /* centred position, overscan on */

/* ── Frameskip ───────────────────────────────────────────────────────── */
static const int FS_MOD[4] = {1, 2, 3, 4};  /* 60 / 30 / 20 / 15 fps */
static int g_frameskip = 1;                  /* default: 30 fps */
static int g_overscan  = 0;                  /* default: off    */

/* ── Buttons (kernel gpio-keys via input_get_buttons()) ───────────────── */
#define BTN_HOME (1u << 1)   /* zephyr,code=1 — no AKIRA_BTN_* for Home/OK */
static int btn_held(uint32_t mask) { return (input_get_buttons() & mask) != 0; }

/* ── Colours (RGB565) ────────────────────────────────────────────────── */
#define C_BLACK   0x0000u
#define C_WHITE   0xFFFFu
#define C_LGRAY   0xC618u
#define C_DGRAY   0x4208u
#define C_DIM     0x528Au

/* ── UI layout ────────────────────────────────────────────────────────── */
#define ROW_H     26
#define MENU_PAD  10
#define HDR_H     22

/* ── Debounced button edge-detect ─────────────────────────────────────────
 * A single-sample "x && !prev" edge check re-fires on mechanical contact
 * bounce: a real press/release can toggle the raw pin several times across
 * consecutive ~16.7ms poll ticks, each toggle looking like a fresh press.
 * deb_edge() requires REL_STABLE consecutive released reads before a button
 * can re-arm, so bounce during release can't be seen as a second press. */
#define REL_STABLE 2
typedef struct { int held, rel_run; } debkey_t;
static int deb_edge(debkey_t *k, int raw)
{
    if (raw) {
        k->rel_run = 0;
        if (!k->held) { k->held = 1; return 1; }
        return 0;
    }
    if (k->rel_run < REL_STABLE) k->rel_run++;
    if (k->rel_run >= REL_STABLE) k->held = 0;
    return 0;
}

/* ── Pause menu ──────────────────────────────────────────────────────── */
#define MENU_RESUME     0
#define MENU_SAVE_STATE 1
#define MENU_LOAD_STATE 2
#define MENU_SETTINGS   3
#define MENU_RESTART    4
#define MENU_EXIT       5
#define MENU_COUNT      6

static const char *MENU_LABELS[MENU_COUNT] = {
    "Resume", "Save State", "Load State", "Settings...", "Restart", "Exit to Menu"
};

/* ── Tiny string helpers ─────────────────────────────────────────────── */
static int satoi(const char *s)
{
    int v = 0;
    while (*s >= '0' && *s <= '9') v = v * 10 + (*s++ - '0');
    return v;
}
static void sitoa(int v, char *b, int max)
{
    if (v == 0) { b[0]='0'; b[1]='\0'; return; }
    char t[8]; int ti=0, i=0;
    while (v>0 && ti<7) { t[ti++]='0'+v%10; v/=10; }
    while (ti-->0 && i<max-1) b[i++]=t[ti];
    b[i]='\0';
}

/* ── Settings persistence ────────────────────────────────────────────── */
static void load_settings(void)
{
    char buf[8];
    if (settings_get("sms/frameskip", buf, sizeof(buf)) == 0) {
        g_frameskip = satoi(buf);
        if (g_frameskip < 0) g_frameskip = 0;
        if (g_frameskip > 3) g_frameskip = 3;
    }
    if (settings_get("sms/overscan", buf, sizeof(buf)) == 0)
        g_overscan = satoi(buf) ? 1 : 0;
}
static void save_int(const char *key, int val)
{
    char buf[8];
    sitoa(val, buf, sizeof(buf));
    settings_set(key, buf);
}

/* ── Display geometry init (queries actual panel size instead of assuming
 * a fixed 320×240 — panels vary across AkiraConsole hardware variants) ── */
static void init_display_geometry(void)
{
    display_get_size(&g_disp_w, &g_disp_h);

    g_sms_dst_x      = (g_disp_w - SMS_W) / 2;
    g_sms_dst_y      = (g_disp_h - SMS_H) / 2;
    g_sms_crop_dst_y = (g_disp_h - SMS_CROP_H) / 2;
    if (g_sms_dst_x < 0)      g_sms_dst_x = 0;
    if (g_sms_dst_y < 0)      g_sms_dst_y = 0;
    if (g_sms_crop_dst_y < 0) g_sms_crop_dst_y = 0;
}

/* ── Border bars ─────────────────────────────────────────────────────────── */
static void draw_border(void)
{
    int img_y = g_overscan ? g_sms_crop_dst_y : g_sms_dst_y;
    int img_h = g_overscan ? SMS_CROP_H        : SMS_H;
    display_rect(0,                    0, g_sms_dst_x,              g_disp_h, 0x0000);
    display_rect(g_sms_dst_x + SMS_W, 0, g_sms_dst_x,              g_disp_h, 0x0000);
    display_rect(0,                    0, g_disp_w,              img_y,        0x0000);
    display_rect(0,           img_y + img_h, g_disp_w, g_disp_h - img_y - img_h, 0x0000);
}

/* ── Draw helpers ─────────────────────────────────────────────────────── */
static void draw_header(int x, int y, int w, const char *title)
{
    display_rect(x, y, w, HDR_H, C_BLACK);
    display_text(x + MENU_PAD, y + 4, title, C_WHITE);
}

static void draw_row(int x, int y, int w,
                     const char *lbl, const char *val, int sel)
{
    uint16_t bg = sel ? C_BLACK : C_WHITE;
    uint16_t fg = sel ? C_WHITE : C_BLACK;
    display_rect(x, y, w, ROW_H, bg);
    display_text(x + MENU_PAD, y + (ROW_H - 8) / 2, lbl, fg);
    if (val && val[0]) {
        int vx = x + w - 60;
        if (vx > x + 80)
            display_text(vx, y + (ROW_H - 8) / 2, val, sel ? C_LGRAY : C_BLACK);
    }
    display_hline(x, y + ROW_H - 1, w, C_LGRAY);
}

/* ── Settings sub-menu ────────────────────────────────────────────────── */
static void show_settings_menu(void)
{
    static const char *FS_LABELS[4] = {
        "Off (60fps)", "Half (30fps)", "1/3 (20fps)", "1/4 (15fps)"
    };
    const int OW = 180;
    const int OH = HDR_H + 3 * ROW_H;  /* Frameskip + Overscan + Back */
    const int OX = (g_disp_w - OW) / 2, OY = (g_disp_h - OH) / 2;

    int cur=0, dirty=1;
    debkey_t ku={.held=btn_held(AKIRA_BTN_UP)},   kd={.held=btn_held(AKIRA_BTN_DOWN)};
    debkey_t ka={.held=btn_held(AKIRA_BTN_A)},    kb={.held=btn_held(AKIRA_BTN_Y)};
    debkey_t kl={.held=btn_held(AKIRA_BTN_LEFT)}, kr={.held=btn_held(AKIRA_BTN_RIGHT)};

    while (1) {
        if (dirty) {
            display_rect(OX-2, OY-2, OW+4, OH+4, C_DGRAY);
            display_rect(OX,   OY,   OW,   OH,   C_WHITE);
            draw_header(OX, OY, OW, "Settings");
            int ry = OY + HDR_H;
            draw_row(OX, ry, OW, "Frame Skip", FS_LABELS[g_frameskip], cur==0); ry += ROW_H;
            draw_row(OX, ry, OW, "Overscan",   g_overscan?"On":"Off",  cur==1); ry += ROW_H;
            draw_row(OX, ry, OW, "Back",       "",                     cur==2);
            display_flush();
            dirty = 0;
        }
        int u=deb_edge(&ku, btn_held(AKIRA_BTN_UP));
        int d=deb_edge(&kd, btn_held(AKIRA_BTN_DOWN));
        int a=deb_edge(&ka, btn_held(AKIRA_BTN_A));
        int b=deb_edge(&kb, btn_held(AKIRA_BTN_Y));
        int l=deb_edge(&kl, btn_held(AKIRA_BTN_LEFT));
        int r=deb_edge(&kr, btn_held(AKIRA_BTN_RIGHT));

        if (u) { cur=(cur+2)%3; dirty=1; }
        if (d) { cur=(cur+1)%3; dirty=1; }
        if (l||r) {
            int delta = r ? 1 : -1;
            if (cur==0) { g_frameskip=(g_frameskip+delta+4)%4; save_int("sms/frameskip",g_frameskip); dirty=1; }
            if (cur==1) { g_overscan^=1; save_int("sms/overscan",g_overscan); dirty=1; }
        }
        if (a) {
            if (cur==0) { g_frameskip=(g_frameskip+1)%4; save_int("sms/frameskip",g_frameskip); dirty=1; }
            else if (cur==1) { g_overscan^=1; save_int("sms/overscan",g_overscan); dirty=1; }
            else break;
        }
        if (b) break;
        delay(20000);
    }
}

/* ── SMS machine (static: avoids stack overflow) ──────────────────────── */
static SMS sms;

/* Briefly shows a standalone status toast, then leaves it to the caller
 * to redraw whatever was on screen (caller must set dirty=1 afterward). */
static void show_pause_status(const char *msg)
{
    const int w = 120, h = ROW_H;
    const int x = (g_disp_w - w) / 2, y = (g_disp_h - h) / 2;
    display_rect(x-2, y-2, w+4, h+4, C_DGRAY);
    display_rect(x,   y,   w,   h,   C_BLACK);
    display_text(x + MENU_PAD, y + (h - 8) / 2, msg, C_WHITE);
    display_flush();
    delay(500000);
}

/* sms_state_{pack,unpack} only marshal to/from a flat buffer (save_state.c
 * can't include akira_api.h — see its header comment), so the actual
 * storage_* I/O happens here. */
static int do_save_state(int slot)
{
    sms_state_pack(&sms);
    int fd = storage_open(save_slot_path(slot), STORAGE_O_WRITE);
    if (fd < 0) return -1;
    int n = storage_write(fd, sms_state_buf(), sms_state_size());
    storage_close(fd);
    return (n == sms_state_size()) ? 0 : -1;
}

static int do_load_state(int slot)
{
    int fd = storage_open(save_slot_path(slot), STORAGE_O_READ);
    if (fd < 0) return -1;
    int n = storage_read(fd, sms_state_buf(), sms_state_size());
    storage_close(fd);
    if (n != sms_state_size()) return -1;
    return sms_state_unpack(&sms);
}

static int save_slot_exists(int slot)
{
    int fd = storage_open(save_slot_path(slot), STORAGE_O_READ);
    if (fd < 0) return 0;
    storage_close(fd);
    return 1;
}

/* Dedicated slot picker: shown when the user chooses Save/Load State from
 * the pause menu, so slot selection is an explicit screen rather than an
 * L/R-while-highlighted gesture the user has to discover. */
static void show_slot_menu(int for_save)
{
    const int OW = 170;
    const int OH = HDR_H + (SAVE_SLOT_COUNT + 1) * ROW_H;
    const int OX = (g_disp_w - OW) / 2, OY = (g_disp_h - OH) / 2;
    const int back_row = SAVE_SLOT_COUNT;

    int cur=0, dirty=1;
    debkey_t ku={.held=btn_held(AKIRA_BTN_UP)}, kd={.held=btn_held(AKIRA_BTN_DOWN)};
    debkey_t ka={.held=btn_held(AKIRA_BTN_A)}, kb={.held=btn_held(AKIRA_BTN_Y)};

    while (1) {
        if (dirty) {
            display_rect(OX-2, OY-2, OW+4, OH+4, C_DGRAY);
            display_rect(OX,   OY,   OW,   OH,   C_WHITE);
            draw_header(OX, OY, OW, for_save ? "Save to Slot" : "Load from Slot");
            int ry = OY + HDR_H;
            char label[8] = "Slot 1";
            for (int i = 0; i < SAVE_SLOT_COUNT; i++) {
                label[5] = (char)('1' + i);
                draw_row(OX, ry, OW, label, save_slot_exists(i) ? "Used" : "Empty", i==cur);
                ry += ROW_H;
            }
            draw_row(OX, ry, OW, "Back", "", cur==back_row);
            display_flush();
            dirty = 0;
        }
        int u=deb_edge(&ku, btn_held(AKIRA_BTN_UP));
        int d=deb_edge(&kd, btn_held(AKIRA_BTN_DOWN));
        int a=deb_edge(&ka, btn_held(AKIRA_BTN_A));
        int b=deb_edge(&kb, btn_held(AKIRA_BTN_Y));

        if (u) { cur=(cur+SAVE_SLOT_COUNT+1-1)%(SAVE_SLOT_COUNT+1); dirty=1; }
        if (d) { cur=(cur+1)%(SAVE_SLOT_COUNT+1);                   dirty=1; }
        if (a) {
            if (cur == back_row) return;
            int rc = for_save ? do_save_state(cur) : do_load_state(cur);
            show_pause_status(rc == 0 ? (for_save ? "Saved!" : "Loaded!")
                                       : (for_save ? "Save failed" : "Load failed"));
            return;
        }
        if (b) return;
        delay(16667);
    }
}

static int show_pause_menu(void)
{
    /* Wait for Settings button release */
    while (btn_held(BTN_HOME)) delay(10000);
    delay(40000);

    const int OW = 170;
    const int OH = HDR_H + MENU_COUNT * ROW_H;
    const int OX = (g_disp_w - OW) / 2, OY = (g_disp_h - OH) / 2;

    int cur=0, dirty=1;
    debkey_t ku={.held=btn_held(AKIRA_BTN_UP)}, kd={.held=btn_held(AKIRA_BTN_DOWN)};
    debkey_t ka={.held=btn_held(AKIRA_BTN_A)},  kb={.held=btn_held(AKIRA_BTN_Y)};
    debkey_t ks={.held=btn_held(BTN_HOME)};

    while (1) {
        if (dirty) {
            /* Slide-in effect: draw overlay from left edge */
            for (int x = OX - 20; x <= OX; x += 8) {
                int cx = x < OX ? x : OX;
                display_rect(cx-2, OY-2, OW+4, OH+4, C_DGRAY);
                display_rect(cx,   OY,   OW,   OH,   C_WHITE);
                draw_header(cx, OY, OW, "PAUSED");
                int ry = OY + HDR_H;
                for (int i = 0; i < MENU_COUNT; i++) {
                    draw_row(cx, ry, OW, MENU_LABELS[i], "", i==cur);
                    ry += ROW_H;
                }
                display_flush();
                delay(8000);
            }
            dirty = 0;
        }
        int s=deb_edge(&ks, btn_held(BTN_HOME));
        int u=deb_edge(&ku, btn_held(AKIRA_BTN_UP));
        int d=deb_edge(&kd, btn_held(AKIRA_BTN_DOWN));
        int a=deb_edge(&ka, btn_held(AKIRA_BTN_A));
        int b=deb_edge(&kb, btn_held(AKIRA_BTN_Y));

        if (s) return MENU_RESUME;
        if (u) { cur=(cur+MENU_COUNT-1)%MENU_COUNT; dirty=1; }
        if (d) { cur=(cur+1)%MENU_COUNT;             dirty=1; }
        if (a) {
            if (cur==MENU_SETTINGS) { show_settings_menu(); dirty=1; continue; }
            if (cur==MENU_SAVE_STATE) { show_slot_menu(1); dirty=1; continue; }
            if (cur==MENU_LOAD_STATE) { show_slot_menu(0); dirty=1; continue; }
            return cur;
        }
        if (b) return MENU_RESUME;
        delay(16667);
    }
}

/* ── Animated boot screen ─────────────────────────────────────────────── */
static void boot_animation(void)
{
    /* CRT warm-up: horizontal line expands from centre outward */
    display_clear(0x0000);
    display_flush();

    int cy = g_disp_h / 2;
    for (int i = 1; i <= 10; i++) {
        int half = (g_disp_h / 2) * i / 10;
        display_rect(0, cy - half, g_disp_w, half * 2, 0x0000);
        display_hline(0, cy - half,     g_disp_w, 0xFFFF);
        display_hline(0, cy + half - 1, g_disp_w, 0xFFFF);
        display_flush();
        delay(15000);
    }

    /* Boot card */
    display_clear(0x0000);
    display_text_large(60, 100, "SMS", 0xFFFF);
    display_text_large(120, 100, "EMULATOR", 0xFFFF);
    display_hline(40, 130, g_disp_w - 80, C_DGRAY);

    /* Loading progress bar */
    const int bx=40, by=140, bw=g_disp_w-80, bh=10;
    display_rect_outline(bx-1, by-1, bw+2, bh+2, C_DGRAY);
    display_flush();

    for (int p = 0; p < bw; p += bw / 24 + 1) {
        int pw = p < bw ? p : bw;
        display_rect(bx, by, pw, bh, 0xFFFF);
        display_flush();
        delay(10000);
    }
    display_rect(bx, by, bw, bh, 0xFFFF);
    display_text(90, by + 20, "Loading ROM...", C_DIM);

    /* Scanline wipe overlay */
    display_flush();
    delay(80000);
    for (int y = 0; y < g_disp_h; y += 10) {
        display_hline(0, y, g_disp_w, C_DGRAY);
    }
    display_flush();
    delay(60000);
    display_clear(0x0000);
    display_flush();
}

/* ── Main ────────────────────────────────────────────────────────────── */
int main(void)
{
    printf("AkiraOS SMS Emulator\n");

    load_settings();
    init_display_geometry();

    boot_animation();

    if (sms_init(&sms, rom_data, rom_size) != 0) {
        display_clear(0x0000);
        display_text(40, 110, "ERROR: ROM init failed", 0xF800);
        display_flush();
        delay(4000000);
        app_switch("supervisor");
        return 1;
    }

    draw_border();
    display_flush();

    debkey_t k_settings = { .held = btn_held(BTN_HOME) };
    int frame_count = 0;

    printf("[SMS] Init OK — entering main loop\n");



    while (1) {
        /* ── Read input ─────────────────────────────────────────────── */
        uint8_t btns = 0;
        if (btn_held(AKIRA_BTN_UP))    btns |= SMS_BTN_UP;
        if (btn_held(AKIRA_BTN_DOWN))  btns |= SMS_BTN_DOWN;
        if (btn_held(AKIRA_BTN_LEFT))  btns |= SMS_BTN_LEFT;
        if (btn_held(AKIRA_BTN_RIGHT)) btns |= SMS_BTN_RIGHT;
        if (btn_held(AKIRA_BTN_A))     btns |= SMS_BTN_1;
        if (btn_held(AKIRA_BTN_Y))     btns |= SMS_BTN_2;
        if (btn_held(AKIRA_BTN_X))     btns |= SMS_BTN_START;  /* Pause/NMI */

        sms_set_buttons(&sms, 0, btns);

        /* ── Pause menu (debounced rising edge) ───────────────────── */
        if (deb_edge(&k_settings, btn_held(BTN_HOME))) {
            int choice = show_pause_menu();
            if (choice == MENU_EXIT) {
                app_switch("supervisor");
                return 0;
            }
            if (choice == MENU_RESTART) {
                sms_init(&sms, rom_data, rom_size);
                draw_border();
                display_flush();
                frame_count = 0;
                printf("[SMS] Restarted\n");
            }
            continue;
        }

        /* ── Run one SMS frame + optional render skip ────────────────── */
        int mod  = FS_MOD[g_frameskip];
        int skip = (frame_count % mod) != 0;
        sms.vdp.skip_render = (uint8_t)skip;
        sms_step_frame(&sms);
        frame_count++;

        /* ── Display ──────────────────────────────────────────────────── */
        if (!skip) {
            if (g_overscan) {
                display_bitmap(g_sms_dst_x, g_sms_crop_dst_y,
                               SMS_W, SMS_CROP_H,
                               (uint8_t *)sms.fb + SMS_W * SMS_OVERSCAN * 2,
                               SMS_W * SMS_CROP_H * 2);
            } else {
                display_bitmap(g_sms_dst_x, g_sms_dst_y,
                               SMS_W, SMS_H,
                               sms.fb, SMS_FB_BYTES);
            }
            display_flush();
        }
    }

    return 0;
}
