/*
 * assets_npcs.h — NPC sprites (16×16 px, 2 frames each, 8 NPCs)
 * Each NPC has frame 0 (standing) and frame 1 (alt / gesture).
 * All facing down by default. TR = transparent (magenta).
 */
#ifndef ASSETS_NPCS_H
#define ASSETS_NPCS_H

#include "assets_palette.h"

/* ── NPC_MAYOR (0) — gray suit, white hair ─── */
static const uint16_t spr_mayor_0[256] = {
    TR, TR, TR, TR, A3, A4, A4, A4, A4, A4, A4, A3, TR, TR, TR, TR,
    TR, TR, TR, A3, A4, A4, A4, A4, A4, A4, A4, A4, A3, TR, TR, TR,
    TR, TR, A3, A4, A4, A4, A4, A4, A4, A4, A4, A4, A4, A3, TR, TR,
    TR, TR, A3, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, A3, TR, TR,
    TR, TR, A3, SK, BK, SK, SK, SK, SK, SK, BK, SK, SK, A3, TR, TR,
    TR, TR, A3, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, A3, TR, TR,
    TR, TR, TR, A3, SK, SK, SK, E1, SK, SK, SK, SK, A3, TR, TR, TR,
    TR, TR, TR, TR, A3, SK, SK, SK, SK, SK, A3, TR, TR, TR, TR, TR,
    TR, TR, TR, A1, A1, A2, A2, A2, A2, A2, A1, A1, TR, TR, TR, TR,
    TR, TR, TR, A1, A2, A2, E1, A2, A2, A2, A2, A1, TR, TR, TR, TR,
    TR, TR, TR, A1, A2, A2, A2, A2, A2, A2, A2, A1, TR, TR, TR, TR,
    TR, TR, TR, A1, A1, A2, A2, A2, A2, A2, A1, A1, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, A2, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, TR, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, A1, A1, TR, A1, A1, BK, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, BK, BK, TR, BK, BK, BK, TR, TR, TR, TR, TR,
};
static const uint16_t spr_mayor_1[256] = {
    TR, TR, TR, TR, A3, A4, A4, A4, A4, A4, A4, A3, TR, TR, TR, TR,
    TR, TR, TR, A3, A4, A4, A4, A4, A4, A4, A4, A4, A3, TR, TR, TR,
    TR, TR, A3, A4, A4, A4, A4, A4, A4, A4, A4, A4, A4, A3, TR, TR,
    TR, TR, A3, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, A3, TR, TR,
    TR, TR, A3, SK, BK, SK, SK, SK, SK, SK, BK, SK, SK, A3, TR, TR,
    TR, TR, A3, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, A3, TR, TR,
    TR, TR, TR, A3, SK, SK, SK, E1, SK, SK, SK, SK, A3, TR, TR, TR,
    TR, TR, TR, TR, A3, SK, SK, SK, SK, SK, A3, TR, TR, TR, TR, TR,
    TR, TR, TR, A1, A1, A2, A2, A2, A2, A2, A1, A1, TR, TR, TR, TR,
    TR, TR, SK, A1, A2, A2, E1, A2, A2, A2, A2, A1, SK, TR, TR, TR,
    TR, TR, TR, A1, A2, A2, A2, A2, A2, A2, A2, A1, TR, TR, TR, TR,
    TR, TR, TR, A1, A1, A2, A2, A2, A2, A2, A1, A1, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, A2, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, TR, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, A1, A1, TR, A1, A1, BK, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, BK, BK, TR, BK, BK, BK, TR, TR, TR, TR, TR,
};

/* ── NPC_ADA (1) — shopkeeper, apron, brown hair ─── */
static const uint16_t spr_ada_0[256] = {
    TR, TR, TR, TR, B1, B1, B1, B1, B1, B1, B1, B1, TR, TR, TR, TR,
    TR, TR, TR, B1, B0, B0, B0, B0, B0, B0, B0, B0, B1, TR, TR, TR,
    TR, TR, B1, B0, B1, B1, B1, B1, B1, B1, B1, B1, B0, B1, TR, TR,
    TR, TR, B1, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B1, TR, TR,
    TR, TR, B1, SK, BK, SK, SK, SK, SK, SK, BK, SK, SK, B1, TR, TR,
    TR, TR, B1, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B1, TR, TR,
    TR, TR, TR, B1, SK, SK, SK, E1, SK, SK, SK, SK, B1, TR, TR, TR,
    TR, TR, TR, TR, B1, SK, SK, SK, SK, SK, B1, TR, TR, TR, TR, TR,
    TR, TR, TR, G2, G2, G3, G3, G3, G3, G3, G2, G2, TR, TR, TR, TR,
    TR, TR, TR, G2, WH, WH, WH, WH, WH, WH, WH, G2, TR, TR, TR, TR,
    TR, TR, TR, G2, WH, WH, WH, WH, WH, WH, WH, G2, TR, TR, TR, TR,
    TR, TR, TR, G2, G2, G3, G3, G3, G3, G3, G2, G2, TR, TR, TR, TR,
    TR, TR, TR, TR, B2, B3, B3, B3, B3, B3, B2, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B2, B3, B3, TR, B3, B3, B2, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B1, B1, TR, B1, B1, B0, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B0, B0, TR, B0, B0, B0, TR, TR, TR, TR, TR,
};
static const uint16_t spr_ada_1[256] = {
    TR, TR, TR, TR, B1, B1, B1, B1, B1, B1, B1, B1, TR, TR, TR, TR,
    TR, TR, TR, B1, B0, B0, B0, B0, B0, B0, B0, B0, B1, TR, TR, TR,
    TR, TR, B1, B0, B1, B1, B1, B1, B1, B1, B1, B1, B0, B1, TR, TR,
    TR, TR, B1, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B1, TR, TR,
    TR, TR, B1, SK, BK, SK, SK, SK, SK, SK, BK, SK, SK, B1, TR, TR,
    TR, TR, B1, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B1, TR, TR,
    TR, TR, TR, B1, SK, SK, SK, SK, SK, SK, SK, SK, B1, TR, TR, TR,
    TR, TR, TR, TR, B1, SK, SK, SK, SK, SK, B1, TR, TR, TR, TR, TR,
    TR, TR, TR, G2, G2, G3, G3, G3, G3, G3, G2, G2, TR, TR, TR, TR,
    TR, TR, SK, G2, WH, WH, WH, WH, WH, WH, WH, G2, SK, TR, TR, TR,
    TR, TR, TR, G2, WH, WH, WH, WH, WH, WH, WH, G2, TR, TR, TR, TR,
    TR, TR, TR, G2, G2, G3, G3, G3, G3, G3, G2, G2, TR, TR, TR, TR,
    TR, TR, TR, TR, B2, B3, B3, B3, B3, B3, B2, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B2, B3, B3, TR, B3, B3, B2, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B1, B1, TR, B1, B1, B0, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B0, B0, TR, B0, B0, B0, TR, TR, TR, TR, TR,
};

/* ── NPC_WHITMORE (2) — librarian, glasses, bow tie ─── */
static const uint16_t spr_whitmore_0[256] = {
    TR, TR, TR, TR, B0, B0, B0, B0, B0, B0, B0, B0, TR, TR, TR, TR,
    TR, TR, TR, B0, A1, A1, A1, A1, A1, A1, A1, A1, B0, TR, TR, TR,
    TR, TR, B0, A1, B0, B0, B0, B0, B0, B0, B0, B0, A1, B0, TR, TR,
    TR, TR, B0, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B0, TR, TR,
    TR, TR, B0, SK, A1, BK, A1, SK, A1, BK, A1, SK, SK, B0, TR, TR,
    TR, TR, B0, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B0, TR, TR,
    TR, TR, TR, B0, SK, SK, SK, E1, SK, SK, SK, SK, B0, TR, TR, TR,
    TR, TR, TR, TR, B0, SK, SK, SK, SK, SK, B0, TR, TR, TR, TR, TR,
    TR, TR, TR, B2, B2, E1, B2, B2, B2, B2, B2, B2, TR, TR, TR, TR,
    TR, TR, TR, B2, B2, B2, B2, B2, B2, B2, B2, B2, TR, TR, TR, TR,
    TR, TR, TR, B2, B2, B2, B2, B2, B2, B2, B2, B2, TR, TR, TR, TR,
    TR, TR, TR, B2, B2, B2, B2, B2, B2, B2, B2, B2, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, A2, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, TR, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, A1, A1, TR, A1, A1, BK, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, BK, BK, TR, BK, BK, BK, TR, TR, TR, TR, TR,
};
static const uint16_t spr_whitmore_1[256] = {
    TR, TR, TR, TR, B0, B0, B0, B0, B0, B0, B0, B0, TR, TR, TR, TR,
    TR, TR, TR, B0, A1, A1, A1, A1, A1, A1, A1, A1, B0, TR, TR, TR,
    TR, TR, B0, A1, B0, B0, B0, B0, B0, B0, B0, B0, A1, B0, TR, TR,
    TR, TR, B0, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B0, TR, TR,
    TR, TR, B0, SK, A1, BK, A1, SK, A1, BK, A1, SK, SK, B0, TR, TR,
    TR, TR, B0, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B0, TR, TR,
    TR, TR, TR, B0, SK, SK, SK, SK, SK, SK, SK, SK, B0, TR, TR, TR,
    TR, TR, TR, TR, B0, SK, SK, SK, SK, SK, B0, TR, TR, TR, TR, TR,
    TR, TR, TR, B2, B2, E1, B2, B2, B2, B2, B2, B2, TR, TR, TR, TR,
    TR, TR, SK, B2, B2, B2, B2, B2, B2, B2, B2, B2, SK, TR, TR, TR,
    TR, TR, TR, B2, B2, B2, B2, B2, B2, B2, B2, B2, TR, TR, TR, TR,
    TR, TR, TR, B2, B2, B2, B2, B2, B2, B2, B2, B2, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, A2, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, TR, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, A1, A1, TR, A1, A1, BK, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, BK, BK, TR, BK, BK, BK, TR, TR, TR, TR, TR,
};

/* ── NPC_PETE (3) — fisherman, hat, scruffy ─── */
static const uint16_t spr_pete_0[256] = {
    TR, TR, TR, B2, B2, B2, B2, B2, B2, B2, B2, B2, B2, TR, TR, TR,
    TR, TR, B2, B3, B3, B3, B3, B3, B3, B3, B3, B3, B3, B2, TR, TR,
    TR, TR, B2, B1, B1, B1, B1, B1, B1, B1, B1, B1, B1, B2, TR, TR,
    TR, TR, B2, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B2, TR, TR,
    TR, TR, B2, SK, BK, SK, SK, SK, SK, SK, BK, SK, SK, B2, TR, TR,
    TR, TR, B2, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B2, TR, TR,
    TR, TR, TR, B2, SK, SK, A2, SK, SK, SK, SK, SK, B2, TR, TR, TR,
    TR, TR, TR, TR, B2, SK, SK, SK, SK, SK, B2, TR, TR, TR, TR, TR,
    TR, TR, TR, B2, B2, B3, B3, B3, B3, B3, B2, B2, TR, TR, TR, TR,
    TR, TR, TR, B2, B3, B3, B3, B3, B3, B3, B3, B2, TR, TR, TR, TR,
    TR, TR, TR, B2, B3, B3, B3, B3, B3, B3, B3, B2, TR, TR, TR, TR,
    TR, TR, TR, B2, B2, B3, B3, B3, B3, B3, B2, B2, TR, TR, TR, TR,
    TR, TR, TR, TR, B1, B2, B2, B2, B2, B2, B1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B1, B2, B2, TR, B2, B2, B1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B1, B1, TR, B1, B1, B0, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B0, B0, TR, B0, B0, B0, TR, TR, TR, TR, TR,
};
static const uint16_t spr_pete_1[256] = {
    TR, TR, TR, B2, B2, B2, B2, B2, B2, B2, B2, B2, B2, TR, TR, TR,
    TR, TR, B2, B3, B3, B3, B3, B3, B3, B3, B3, B3, B3, B2, TR, TR,
    TR, TR, B2, B1, B1, B1, B1, B1, B1, B1, B1, B1, B1, B2, TR, TR,
    TR, TR, B2, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B2, TR, TR,
    TR, TR, B2, SK, BK, SK, SK, SK, SK, SK, BK, SK, SK, B2, TR, TR,
    TR, TR, B2, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, B2, TR, TR,
    TR, TR, TR, B2, SK, SK, A2, SK, SK, SK, SK, SK, B2, TR, TR, TR,
    TR, TR, TR, TR, B2, SK, SK, SK, SK, SK, B2, TR, TR, TR, TR, TR,
    TR, TR, TR, B2, B2, B3, B3, B3, B3, B3, B2, B2, TR, TR, TR, TR,
    TR, TR, SK, B2, B3, B3, B3, B3, B3, B3, B3, B2, SK, TR, TR, TR,
    TR, TR, TR, B2, B3, B3, B3, B3, B3, B3, B3, B2, TR, TR, TR, TR,
    TR, TR, TR, B2, B2, B3, B3, B3, B3, B3, B2, B2, TR, TR, TR, TR,
    TR, TR, TR, TR, B1, B2, B2, B2, B2, B2, B1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B1, B2, B2, TR, B2, B2, B1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B1, B1, TR, B1, B1, B0, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B0, B0, TR, B0, B0, B0, TR, TR, TR, TR, TR,
};

/* ── NPC_ELARA (4) — scientist, lab coat, dark hair ─── */
static const uint16_t spr_elara_0[256] = {
    TR, TR, TR, TR, BK, BK, BK, BK, BK, BK, BK, BK, TR, TR, TR, TR,
    TR, TR, TR, BK, A0, A0, A0, A0, A0, A0, A0, A0, BK, TR, TR, TR,
    TR, TR, BK, A0, BK, BK, BK, BK, BK, BK, BK, BK, A0, BK, TR, TR,
    TR, TR, BK, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, BK, TR, TR,
    TR, TR, BK, SK, BK, SK, SK, SK, SK, SK, BK, SK, SK, BK, TR, TR,
    TR, TR, BK, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, BK, TR, TR,
    TR, TR, TR, BK, SK, SK, SK, E1, SK, SK, SK, SK, BK, TR, TR, TR,
    TR, TR, TR, TR, BK, SK, SK, SK, SK, SK, BK, TR, TR, TR, TR, TR,
    TR, TR, TR, WH, WH, A4, A4, A4, A4, A4, WH, WH, TR, TR, TR, TR,
    TR, TR, TR, WH, A4, A4, A4, A4, A4, A4, A4, WH, TR, TR, TR, TR,
    TR, TR, TR, WH, A4, A4, A4, A4, A4, A4, A4, WH, TR, TR, TR, TR,
    TR, TR, TR, WH, WH, A4, A4, A4, A4, A4, WH, WH, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, A2, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, TR, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, A1, A1, TR, A1, A1, BK, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, BK, BK, TR, BK, BK, BK, TR, TR, TR, TR, TR,
};
static const uint16_t spr_elara_1[256] = {
    TR, TR, TR, TR, BK, BK, BK, BK, BK, BK, BK, BK, TR, TR, TR, TR,
    TR, TR, TR, BK, A0, A0, A0, A0, A0, A0, A0, A0, BK, TR, TR, TR,
    TR, TR, BK, A0, BK, BK, BK, BK, BK, BK, BK, BK, A0, BK, TR, TR,
    TR, TR, BK, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, BK, TR, TR,
    TR, TR, BK, SK, BK, SK, SK, SK, SK, SK, BK, SK, SK, BK, TR, TR,
    TR, TR, BK, SK, SK, SK, SK, SK, SK, SK, SK, SK, SK, BK, TR, TR,
    TR, TR, TR, BK, SK, SK, SK, SK, SK, SK, SK, SK, BK, TR, TR, TR,
    TR, TR, TR, TR, BK, SK, SK, SK, SK, SK, BK, TR, TR, TR, TR, TR,
    TR, TR, TR, WH, WH, A4, A4, A4, A4, A4, WH, WH, TR, TR, TR, TR,
    TR, TR, SK, WH, A4, A4, A4, A4, A4, A4, A4, WH, SK, TR, TR, TR,
    TR, TR, TR, WH, A4, A4, A4, A4, A4, A4, A4, WH, TR, TR, TR, TR,
    TR, TR, TR, WH, WH, A4, A4, A4, A4, A4, WH, WH, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, A2, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, A1, A2, A2, TR, A2, A2, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, A1, A1, TR, A1, A1, BK, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, BK, BK, BK, TR, BK, BK, BK, TR, TR, TR, TR, TR,
};

/* ── NPC_OLD_MAN (5) — hooded cloak, mysterious ─── */
static const uint16_t spr_oldman_0[256] = {
    TR, TR, TR, TR, A1, A1, A1, A1, A1, A1, A1, A1, TR, TR, TR, TR,
    TR, TR, TR, A1, A2, A2, A2, A2, A2, A2, A2, A2, A1, TR, TR, TR,
    TR, TR, A1, A2, A2, A2, A2, A2, A2, A2, A2, A2, A2, A1, TR, TR,
    TR, TR, A1, A2, SK, SK, SK, SK, SK, SK, SK, SK, A2, A1, TR, TR,
    TR, TR, A1, A2, BK, SK, SK, SK, SK, SK, BK, SK, A2, A1, TR, TR,
    TR, TR, A1, A2, SK, SK, SK, SK, SK, SK, SK, SK, A2, A1, TR, TR,
    TR, TR, TR, A1, SK, A3, A3, SK, SK, SK, SK, SK, A1, TR, TR, TR,
    TR, TR, TR, TR, A1, SK, SK, SK, SK, SK, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, A1, A1, A2, A2, A2, A2, A2, A1, A1, TR, TR, TR, TR,
    TR, TR, A1, A1, A2, A2, A2, A2, A2, A2, A2, A1, A1, TR, TR, TR,
    TR, TR, A1, A2, A2, A2, A2, A2, A2, A2, A2, A2, A1, TR, TR, TR,
    TR, TR, A1, A2, A2, A2, A2, A2, A2, A2, A2, A2, A1, TR, TR, TR,
    TR, TR, A1, A1, A2, A2, A2, A2, A2, A2, A2, A1, A1, TR, TR, TR,
    TR, TR, TR, A1, A2, A2, A2, TR, A2, A2, A2, A1, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B1, B1, TR, B1, B1, B0, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B0, B0, TR, B0, B0, B0, TR, TR, TR, TR, TR,
};
static const uint16_t spr_oldman_1[256] = {
    TR, TR, TR, TR, A1, A1, A1, A1, A1, A1, A1, A1, TR, TR, TR, TR,
    TR, TR, TR, A1, A2, A2, A2, A2, A2, A2, A2, A2, A1, TR, TR, TR,
    TR, TR, A1, A2, A2, A2, A2, A2, A2, A2, A2, A2, A2, A1, TR, TR,
    TR, TR, A1, A2, SK, SK, SK, SK, SK, SK, SK, SK, A2, A1, TR, TR,
    TR, TR, A1, A2, BK, SK, SK, SK, SK, SK, BK, SK, A2, A1, TR, TR,
    TR, TR, A1, A2, SK, SK, SK, SK, SK, SK, SK, SK, A2, A1, TR, TR,
    TR, TR, TR, A1, SK, A3, A3, SK, SK, SK, SK, SK, A1, TR, TR, TR,
    TR, TR, TR, TR, A1, SK, SK, SK, SK, SK, A1, TR, TR, TR, TR, TR,
    TR, TR, TR, A1, A1, A2, A2, A2, A2, A2, A1, A1, TR, TR, TR, TR,
    TR, TR, A1, A1, A2, A2, A2, A2, A2, A2, A2, A1, A1, SK, TR, TR,
    TR, TR, A1, A2, A2, A2, A2, A2, A2, A2, A2, A2, A1, TR, TR, TR,
    TR, TR, A1, A2, A2, A2, A2, A2, A2, A2, A2, A2, A1, TR, TR, TR,
    TR, TR, A1, A1, A2, A2, A2, A2, A2, A2, A2, A1, A1, TR, TR, TR,
    TR, TR, TR, A1, A2, A2, A2, TR, A2, A2, A2, A1, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B1, B1, TR, B1, B1, B0, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, B0, B0, B0, TR, B0, B0, B0, TR, TR, TR, TR, TR,
};

/* ── NPC_TOMMY (6) — kid, cap, smaller ─── */
static const uint16_t spr_tommy_0[256] = {
    TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, E1, E1, E1, E1, E1, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, E1, E0, E0, E0, E0, E0, E1, TR, TR, TR, TR, TR,
    TR, TR, TR, E1, B1, B1, B1, B1, B1, B1, B1, E1, TR, TR, TR, TR,
    TR, TR, TR, E1, SK, SK, SK, SK, SK, SK, SK, E1, TR, TR, TR, TR,
    TR, TR, TR, E1, BK, SK, SK, SK, SK, BK, SK, E1, TR, TR, TR, TR,
    TR, TR, TR, E1, SK, SK, SK, SK, SK, SK, SK, E1, TR, TR, TR, TR,
    TR, TR, TR, TR, E1, SK, E1, SK, SK, SK, E1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, E1, SK, SK, SK, E1, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, G3, G4, G4, G4, G4, G4, G3, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, G3, G4, G4, G4, G4, G4, G3, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, L1, L2, L2, L2, L1, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, L1, L2, TR, L2, L1, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, B0, B1, TR, B1, B0, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, B0, B0, TR, B0, B0, TR, TR, TR, TR, TR, TR,
};
static const uint16_t spr_tommy_1[256] = {
    TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, E1, E1, E1, E1, E1, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, E1, E0, E0, E0, E0, E0, E1, TR, TR, TR, TR, TR,
    TR, TR, TR, E1, B1, B1, B1, B1, B1, B1, B1, E1, TR, TR, TR, TR,
    TR, TR, TR, E1, SK, SK, SK, SK, SK, SK, SK, E1, TR, TR, TR, TR,
    TR, TR, TR, E1, BK, SK, SK, SK, SK, BK, SK, E1, TR, TR, TR, TR,
    TR, TR, TR, E1, SK, SK, SK, SK, SK, SK, SK, E1, TR, TR, TR, TR,
    TR, TR, TR, TR, E1, SK, E1, SK, SK, SK, E1, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, E1, SK, SK, SK, E1, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, G3, G4, G4, G4, G4, G4, G3, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, G3, G4, G4, G4, G4, G4, G3, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, L1, L2, L2, TR, L2, L2, L1, TR, TR, TR, TR, TR,
    TR, TR, TR, B0, L1, L2, TR, TR, TR, L2, L1, B0, TR, TR, TR, TR,
    TR, TR, B0, B0, B1, TR, TR, TR, TR, TR, B1, B0, B0, TR, TR, TR,
    TR, TR, B0, TR, TR, TR, TR, TR, TR, TR, TR, TR, B0, TR, TR, TR,
};

/* ── NPC_GHOST (7) — translucent elder, blue tint ─── */
static const uint16_t spr_ghost_0[256] = {
    TR, TR, TR, TR, L3, L3, L3, L3, L3, L3, L3, L3, TR, TR, TR, TR,
    TR, TR, TR, L3, L2, L2, L2, L2, L2, L2, L2, L2, L3, TR, TR, TR,
    TR, TR, L3, L2, L3, L3, L3, L3, L3, L3, L3, L3, L2, L3, TR, TR,
    TR, TR, L3, L2, L3, L3, L3, L3, L3, L3, L3, L3, L2, L3, TR, TR,
    TR, TR, L3, L2, WH, L3, L3, L3, L3, L3, WH, L3, L2, L3, TR, TR,
    TR, TR, L3, L2, L3, L3, L3, L3, L3, L3, L3, L3, L2, L3, TR, TR,
    TR, TR, TR, L3, L2, L3, L3, L3, L3, L3, L2, L3, TR, TR, TR, TR,
    TR, TR, TR, TR, L3, L2, L3, L3, L3, L2, L3, TR, TR, TR, TR, TR,
    TR, TR, TR, L3, L3, L2, L2, L2, L2, L2, L3, L3, TR, TR, TR, TR,
    TR, TR, TR, L3, L2, L2, L2, L2, L2, L2, L2, L3, TR, TR, TR, TR,
    TR, TR, TR, L3, L2, L2, L2, L2, L2, L2, L2, L3, TR, TR, TR, TR,
    TR, TR, TR, L3, L3, L2, L2, L2, L2, L2, L3, L3, TR, TR, TR, TR,
    TR, TR, TR, TR, L3, L2, L2, L2, L2, L2, L3, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, L3, L3, L2, TR, L2, L3, L3, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, L3, L3, TR, L3, L3, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, TR, L3, TR, L3, TR, TR, TR, TR, TR, TR, TR,
};
static const uint16_t spr_ghost_1[256] = {
    TR, TR, TR, TR, L3, L3, L3, L3, L3, L3, L3, L3, TR, TR, TR, TR,
    TR, TR, TR, L3, L2, L2, L2, L2, L2, L2, L2, L2, L3, TR, TR, TR,
    TR, TR, L3, L2, L3, L3, L3, L3, L3, L3, L3, L3, L2, L3, TR, TR,
    TR, TR, L3, L2, L3, L3, L3, L3, L3, L3, L3, L3, L2, L3, TR, TR,
    TR, TR, L3, L2, WH, L3, L3, L3, L3, L3, WH, L3, L2, L3, TR, TR,
    TR, TR, L3, L2, L3, L3, L3, L3, L3, L3, L3, L3, L2, L3, TR, TR,
    TR, TR, TR, L3, L2, L3, L3, WH, L3, L3, L2, L3, TR, TR, TR, TR,
    TR, TR, TR, TR, L3, L2, L3, L3, L3, L2, L3, TR, TR, TR, TR, TR,
    TR, TR, TR, L3, L3, L2, L2, L2, L2, L2, L3, L3, TR, TR, TR, TR,
    TR, TR, TR, L3, L2, L2, L2, L2, L2, L2, L2, L3, TR, TR, TR, TR,
    TR, TR, TR, L3, L2, L2, L2, L2, L2, L2, L2, L3, TR, TR, TR, TR,
    TR, TR, TR, L3, L3, L2, L2, L2, L2, L2, L3, L3, TR, TR, TR, TR,
    TR, TR, TR, TR, L3, L2, L2, L2, L2, L2, L3, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, L3, L3, L2, TR, L2, L3, L3, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, L3, L3, TR, L3, L3, TR, TR, TR, TR, TR, TR,
    TR, TR, TR, TR, TR, TR, L3, TR, L3, TR, TR, TR, TR, TR, TR, TR,
};

/* NPC sprite lookup: npc_sprites[npc_id * 2 + frame] */
static const uint16_t * const npc_sprites[16] = {
    spr_mayor_0,   spr_mayor_1,
    spr_ada_0,     spr_ada_1,
    spr_whitmore_0,spr_whitmore_1,
    spr_pete_0,    spr_pete_1,
    spr_elara_0,   spr_elara_1,
    spr_oldman_0,  spr_oldman_1,
    spr_tommy_0,   spr_tommy_1,
    spr_ghost_0,   spr_ghost_1,
};

#endif /* ASSETS_NPCS_H */
