/*
 * world.c — Glasses Mystery: All screen data (RLE maps, doors, NPCs, items)
 *
 * 34 screens total.  Outdoor screens are arranged on a rough grid;
 * indoor screens are reached only through doors.
 *
 * RLE format: [count, tile_id, count, tile_id, ...]
 * Each screen decodes to 40×30 = 1200 tiles, but only 40×27 = 1080 are
 * used for gameplay (bottom 3 rows = HUD area, filled with T_GRASS).
 */

#include "engine.h"
#include "world.h"

/* ═══════════════════════════════════════════════════════════════════════════
 *  Current screen state
 * ═══════════════════════════════════════════════════════════════════════════ */
uint8_t current_tiles[TILES_X * TILES_Y];
uint8_t current_screen_id = 0;

/* ═══════════════════════════════════════════════════════════════════════════
 *  Helper: simple memcpy (no stdlib)
 * ═══════════════════════════════════════════════════════════════════════════ */
static void mcpy(void *dst, const void *src, int n) {
    uint8_t *d = (uint8_t *)dst;
    const uint8_t *s = (const uint8_t *)src;
    while (n-- > 0) *d++ = *s++;
}

/* ═══════════════════════════════════════════════════════════════════════════
 *  RLE DATA — compact tile maps for each screen
 *
 *  For brevity, smaller/simpler indoor rooms use short RLE blocks.
 *  Outdoor screens are larger and more detailed.
 * ═══════════════════════════════════════════════════════════════════════════ */

/* ── SCR_FOREST_NW (0) ── Dense forest, NW corner ──────────────────────── */
static const uint8_t rle_forest_nw[] = {
    /* Row 0-2: thick tree line at top */
    5, T_TREE_TL, 5, T_TREE_TR, 10, T_TREE_TL, 10, T_TREE_TR, 5, T_TREE_TL, 5, T_TREE_TR,
    5, T_TREE_BL, 5, T_TREE_BR, 10, T_TREE_BL, 10, T_TREE_BR, 5, T_TREE_BL, 5, T_TREE_BR,
    /* Row 2-4: trees + grass */
    2, T_TREE_TL, 2, T_TREE_TR, 6, T_GRASS, 2, T_BUSH, 6, T_GRASS, 2, T_TREE_TL, 2, T_TREE_TR, 8, T_GRASS, 4, T_TALL_GRASS, 6, T_GRASS,
    2, T_TREE_BL, 2, T_TREE_BR, 6, T_GRASS2, 2, T_FLOWER, 6, T_GRASS, 2, T_TREE_BL, 2, T_TREE_BR, 8, T_GRASS2, 4, T_GRASS, 6, T_GRASS2,
    /* Row 4-6: open area with path */
    10, T_GRASS, 2, T_ROCK, 8, T_GRASS, 2, T_TREE_TL, 2, T_TREE_TR, 6, T_GRASS, 4, T_TALL_GRASS, 6, T_GRASS,
    8, T_GRASS, 2, T_GRASS2, 2, T_GRASS, 8, T_GRASS2, 2, T_TREE_BL, 2, T_TREE_BR, 6, T_GRASS2, 4, T_GRASS, 6, T_GRASS,
    /* Row 6-8: path going south-east */
    6, T_GRASS, 4, T_TALL_GRASS, 6, T_GRASS, 4, T_PATH_H, 4, T_GRASS, 4, T_BUSH, 6, T_GRASS, 6, T_GRASS2,
    4, T_GRASS2, 6, T_GRASS, 6, T_GRASS2, 4, T_PATH_H, 4, T_GRASS, 4, T_GRASS2, 6, T_GRASS, 6, T_GRASS,
    /* Row 8-12: more forest */
    2, T_TREE_TL, 2, T_TREE_TR, 6, T_GRASS, 2, T_ROCK, 4, T_GRASS, 4, T_PATH_H, 4, T_GRASS, 6, T_GRASS2, 4, T_TALL_GRASS, 6, T_GRASS,
    2, T_TREE_BL, 2, T_TREE_BR, 6, T_GRASS2, 2, T_GRASS, 4, T_GRASS2, 4, T_PATH_H, 4, T_GRASS, 6, T_GRASS, 4, T_GRASS2, 6, T_GRASS,
    10, T_GRASS, 4, T_FLOWER, 6, T_GRASS, 4, T_PATH_V, 4, T_GRASS, 2, T_TREE_TL, 2, T_TREE_TR, 4, T_GRASS, 4, T_GRASS2,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS2, 4, T_PATH_V, 4, T_GRASS2, 2, T_TREE_BL, 2, T_TREE_BR, 4, T_GRASS, 4, T_GRASS,
    /* Row 12-16 */
    6, T_GRASS, 2, T_BUSH, 6, T_GRASS, 6, T_GRASS2, 4, T_PATH_V, 10, T_GRASS, 6, T_GRASS2,
    6, T_GRASS2, 4, T_GRASS, 4, T_TREE_TL, 4, T_TREE_TR, 2, T_GRASS, 4, T_PATH_V, 10, T_GRASS2, 6, T_GRASS,
    6, T_GRASS, 4, T_GRASS2, 4, T_TREE_BL, 4, T_TREE_BR, 2, T_GRASS2, 4, T_PATH_V, 10, T_GRASS, 6, T_GRASS2,
    6, T_GRASS2, 2, T_TALL_GRASS, 2, T_GRASS, 10, T_GRASS, 2, T_GRASS2, 4, T_PATH_V, 8, T_GRASS2, 6, T_GRASS,
    /* Row 16-20 */
    4, T_GRASS, 4, T_TALL_GRASS, 12, T_GRASS, 4, T_PATH_V, 4, T_GRASS, 2, T_ROCK, 4, T_GRASS2, 6, T_GRASS,
    4, T_GRASS2, 4, T_GRASS, 12, T_GRASS2, 4, T_PATH_V, 4, T_GRASS2, 6, T_GRASS, 6, T_GRASS2,
    6, T_GRASS, 2, T_BUSH, 12, T_GRASS, 4, T_PATH_V, 4, T_GRASS, 6, T_GRASS2, 6, T_GRASS,
    6, T_GRASS2, 4, T_GRASS, 10, T_GRASS2, 4, T_PATH_V, 4, T_GRASS2, 6, T_GRASS, 6, T_GRASS,
    /* Row 20-24 */
    4, T_TREE_TL, 4, T_TREE_TR, 6, T_GRASS, 6, T_GRASS2, 4, T_PATH_V, 10, T_GRASS, 6, T_GRASS2,
    4, T_TREE_BL, 4, T_TREE_BR, 6, T_GRASS2, 6, T_GRASS, 4, T_PATH_V, 10, T_GRASS2, 6, T_GRASS,
    10, T_GRASS, 4, T_TALL_GRASS, 6, T_GRASS, 4, T_PATH_V, 4, T_GRASS, 6, T_GRASS, 6, T_GRASS2,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS2, 4, T_PATH_H, 4, T_PATH_H, 4, T_PATH_H, 8, T_PATH_H, 6, T_PATH_H,
    /* Row 24-27: path exits south and east */
    10, T_GRASS, 4, T_GRASS2, 6, T_GRASS, 20, T_GRASS2,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS2, 20, T_GRASS,
    10, T_GRASS, 4, T_TALL_GRASS, 26, T_GRASS,
    /* HUD rows 27-29 */
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_FOREST_N (1) ── Forest, north edge ─────────────────────────────── */
static const uint8_t rle_forest_n[] = {
    /* Top tree line */
    20, T_TREE_TL, 20, T_TREE_TR,
    20, T_TREE_BL, 20, T_TREE_BR,
    /* Open area with scattered trees */
    10, T_GRASS, 2, T_BUSH, 8, T_GRASS, 2, T_ROCK, 8, T_GRASS2, 4, T_TALL_GRASS, 6, T_GRASS,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS, 4, T_GRASS2, 6, T_GRASS, 4, T_GRASS2, 6, T_GRASS2,
    /* Path horizontal through middle */
    40, T_PATH_H,
    6, T_GRASS, 4, T_TREE_TL, 4, T_TREE_TR, 6, T_GRASS2, 4, T_TALL_GRASS, 6, T_GRASS, 4, T_FLOWER, 6, T_GRASS2,
    6, T_GRASS2, 4, T_TREE_BL, 4, T_TREE_BR, 6, T_GRASS, 4, T_GRASS, 6, T_GRASS2, 4, T_GRASS, 6, T_GRASS,
    10, T_GRASS, 4, T_BUSH, 6, T_GRASS2, 10, T_GRASS, 4, T_ROCK, 6, T_GRASS,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS, 10, T_GRASS2, 4, T_GRASS, 6, T_GRASS2,
    /* More trees */
    2, T_TREE_TL, 2, T_TREE_TR, 16, T_GRASS, 2, T_TREE_TL, 2, T_TREE_TR, 6, T_GRASS, 4, T_TALL_GRASS, 6, T_GRASS,
    2, T_TREE_BL, 2, T_TREE_BR, 16, T_GRASS2, 2, T_TREE_BL, 2, T_TREE_BR, 6, T_GRASS2, 4, T_GRASS, 6, T_GRASS2,
    10, T_GRASS, 4, T_FLOWER, 16, T_GRASS, 4, T_GRASS2, 6, T_GRASS,
    10, T_GRASS2, 4, T_GRASS, 16, T_GRASS2, 4, T_GRASS, 6, T_GRASS,
    6, T_GRASS, 2, T_BUSH, 12, T_GRASS2, 2, T_ROCK, 8, T_GRASS, 4, T_TALL_GRASS, 6, T_GRASS2,
    6, T_GRASS2, 4, T_GRASS, 10, T_GRASS, 4, T_GRASS2, 6, T_GRASS2, 4, T_GRASS, 6, T_GRASS,
    /* Sign post and path down */
    12, T_GRASS, 2, T_SIGN, 6, T_GRASS, 4, T_PATH_V, 6, T_GRASS2, 4, T_GRASS, 6, T_GRASS2,
    12, T_GRASS2, 2, T_GRASS, 6, T_GRASS2, 4, T_PATH_V, 6, T_GRASS, 4, T_GRASS2, 6, T_GRASS,
    10, T_GRASS, 4, T_GRASS, 6, T_GRASS, 4, T_PATH_V, 10, T_GRASS, 6, T_GRASS,
    10, T_GRASS2, 4, T_GRASS2, 6, T_GRASS2, 4, T_PATH_V, 10, T_GRASS2, 6, T_GRASS2,
    10, T_GRASS, 4, T_TALL_GRASS, 6, T_GRASS, 4, T_PATH_V, 10, T_GRASS, 6, T_GRASS,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS2, 4, T_PATH_V, 10, T_GRASS2, 6, T_GRASS2,
    10, T_GRASS, 4, T_GRASS2, 6, T_GRASS, 4, T_PATH_V, 10, T_GRASS, 6, T_GRASS,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS2, 4, T_PATH_V, 10, T_GRASS2, 6, T_GRASS2,
    10, T_GRASS, 4, T_GRASS, 6, T_GRASS, 4, T_PATH_V, 10, T_GRASS, 6, T_GRASS,
    /* HUD */
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_FOREST_NE (2) ── Forest NE, cave entrance visible ─────────────── */
static const uint8_t rle_forest_ne[] = {
    20, T_TREE_TL, 20, T_TREE_TR,
    20, T_TREE_BL, 20, T_TREE_BR,
    10, T_GRASS, 10, T_TALL_GRASS, 10, T_GRASS, 10, T_GRASS2,
    10, T_GRASS2, 10, T_GRASS, 10, T_GRASS2, 10, T_GRASS,
    6, T_GRASS, 4, T_BUSH, 10, T_GRASS, 10, T_ROCK, 10, T_GRASS,
    6, T_GRASS2, 4, T_GRASS, 10, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    10, T_GRASS, 10, T_GRASS2, 10, T_GRASS, 2, T_TREE_TL, 2, T_TREE_TR, 6, T_GRASS2,
    10, T_GRASS2, 10, T_GRASS, 10, T_GRASS2, 2, T_TREE_BL, 2, T_TREE_BR, 6, T_GRASS,
    20, T_GRASS, 10, T_TALL_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    10, T_GRASS, 4, T_FLOWER, 6, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    10, T_GRASS, 2, T_TREE_TL, 2, T_TREE_TR, 16, T_GRASS, 10, T_GRASS2,
    10, T_GRASS2, 2, T_TREE_BL, 2, T_TREE_BR, 16, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    20, T_GRASS, 10, T_TALL_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    40, T_GRASS, 40, T_GRASS,
    40, T_GRASS,
};

/* ── SCR_MANSION_EXT (3) ── Mansion exterior, iron gate ─────────────────── */
static const uint8_t rle_mansion_ext[] = {
    20, T_TREE_TL, 20, T_TREE_TR,
    20, T_TREE_BL, 20, T_TREE_BR,
    10, T_GRASS, 20, T_FENCE_H, 10, T_GRASS,
    10, T_GRASS, 2, T_FENCE_V, 16, T_STONE, 2, T_FENCE_V, 10, T_GRASS,
    10, T_GRASS, 2, T_FENCE_V, 16, T_STONE, 2, T_FENCE_V, 10, T_GRASS,
    /* Mansion facade */
    10, T_GRASS, 2, T_FENCE_V, 2, T_STONE, 2, T_ROOF, 2, T_ROOF, 2, T_ROOF, 2, T_ROOF, 2, T_CHIMNEY, 2, T_ROOF, 2, T_STONE, 2, T_FENCE_V, 10, T_GRASS,
    10, T_GRASS, 2, T_FENCE_V, 2, T_STONE, 2, T_WALL_TOP, 2, T_WALL_TOP, 2, T_WINDOW, 2, T_WALL_TOP, 2, T_WALL_TOP, 2, T_WINDOW, 2, T_STONE, 2, T_FENCE_V, 10, T_GRASS,
    10, T_GRASS, 2, T_FENCE_V, 2, T_STONE, 2, T_WALL_SIDE, 2, T_WALL_SIDE, 2, T_WALL_SIDE, 2, T_DOOR_CLOSED, 2, T_WALL_SIDE, 2, T_WALL_SIDE, 2, T_STONE, 2, T_FENCE_V, 10, T_GRASS,
    10, T_GRASS, 2, T_FENCE_V, 16, T_STONE, 2, T_FENCE_V, 10, T_GRASS,
    10, T_GRASS, 2, T_FENCE_V, 6, T_STONE, 4, T_DOOR_CLOSED, 6, T_STONE, 2, T_FENCE_V, 10, T_GRASS,
    10, T_GRASS, 20, T_FENCE_H, 10, T_GRASS,
    /* Garden */
    10, T_GRASS, 4, T_FLOWER, 12, T_GRASS, 4, T_FLOWER, 10, T_GRASS2,
    10, T_GRASS2, 4, T_GRASS, 12, T_GRASS2, 4, T_GRASS, 10, T_GRASS,
    10, T_GRASS, 2, T_LAMP, 8, T_PATH_H, 2, T_PATH_H, 8, T_PATH_H, 2, T_LAMP, 8, T_GRASS,
    10, T_GRASS2, 10, T_GRASS, 10, T_GRASS2, 10, T_GRASS,
    10, T_GRASS, 10, T_GRASS2, 10, T_GRASS, 10, T_GRASS2,
    10, T_GRASS2, 4, T_BUSH, 6, T_GRASS, 10, T_GRASS2, 4, T_BUSH, 6, T_GRASS,
    /* Remainder */
    40, T_GRASS, 40, T_GRASS2, 40, T_GRASS, 40, T_GRASS2,
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS2,
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_LAKE_W (4) ── Lake west shore ──────────────────────────────────── */
static const uint8_t rle_lake_w[] = {
    20, T_GRASS, 10, T_WATER_EDGE_N, 10, T_WATER,
    20, T_GRASS2, 10, T_WATER, 10, T_WATER_DEEP,
    10, T_GRASS, 4, T_TALL_GRASS, 6, T_GRASS, 10, T_WATER, 10, T_WATER_DEEP,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS2, 10, T_WATER, 10, T_WATER_DEEP,
    6, T_GRASS, 4, T_BUSH, 10, T_GRASS, 10, T_WATER, 10, T_WATER_DEEP,
    6, T_GRASS2, 4, T_GRASS, 10, T_GRASS2, 10, T_WATER, 10, T_WATER_DEEP,
    /* Beach strip at edge */
    20, T_GRASS, 4, T_SAND, 6, T_WATER_EDGE_W, 10, T_WATER,
    20, T_GRASS2, 4, T_SAND, 6, T_WATER, 10, T_WATER_DEEP,
    10, T_GRASS, 2, T_ROCK, 8, T_GRASS, 4, T_SAND, 6, T_WATER, 10, T_WATER,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS2, 4, T_SAND, 6, T_WATER, 10, T_WATER_DEEP,
    20, T_GRASS, 4, T_SAND, 6, T_WATER_EDGE_W, 10, T_WATER,
    20, T_GRASS2, 4, T_SAND, 6, T_WATER, 10, T_WATER_DEEP,
    10, T_GRASS, 4, T_FLOWER, 6, T_GRASS, 4, T_SAND, 6, T_WATER, 10, T_WATER,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS2, 4, T_SAND, 6, T_WATER, 10, T_WATER_DEEP,
    20, T_GRASS, 4, T_SAND, 6, T_WATER, 10, T_WATER,
    20, T_GRASS2, 4, T_SAND, 6, T_WATER, 10, T_WATER_DEEP,
    20, T_GRASS, 4, T_SAND, 6, T_WATER, 10, T_WATER,
    20, T_GRASS2, 4, T_SAND, 6, T_WATER, 10, T_WATER_DEEP,
    20, T_GRASS, 4, T_SAND, 16, T_WATER,
    20, T_GRASS2, 4, T_SAND, 16, T_WATER_DEEP,
    20, T_GRASS, 4, T_SAND, 16, T_WATER,
    20, T_GRASS2, 4, T_SAND, 16, T_WATER_DEEP,
    20, T_GRASS, 4, T_SAND, 16, T_WATER,
    20, T_GRASS2, 20, T_WATER_EDGE_S,
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_FOREST_W (5) ── ─────────────────────────────────────────────────── */
static const uint8_t rle_forest_w[] = {
    2, T_TREE_TL, 2, T_TREE_TR, 36, T_GRASS,
    2, T_TREE_BL, 2, T_TREE_BR, 36, T_GRASS2,
    10, T_GRASS, 4, T_TALL_GRASS, 26, T_GRASS,
    10, T_GRASS2, 4, T_GRASS, 26, T_GRASS2,
    6, T_GRASS, 4, T_BUSH, 20, T_GRASS, 4, T_TALL_GRASS, 6, T_GRASS,
    6, T_GRASS2, 4, T_GRASS, 20, T_GRASS2, 4, T_GRASS, 6, T_GRASS2,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    2, T_TREE_TL, 2, T_TREE_TR, 6, T_GRASS, 4, T_FLOWER, 6, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    2, T_TREE_BL, 2, T_TREE_BR, 6, T_GRASS2, 4, T_GRASS, 6, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    40, T_GRASS, 40, T_GRASS2,
    10, T_GRASS, 2, T_ROCK, 28, T_GRASS, 10, T_GRASS2, 2, T_GRASS, 28, T_GRASS2,
    40, T_GRASS, 40, T_GRASS2, 40, T_GRASS, 40, T_GRASS2,
    10, T_GRASS, 2, T_BUSH, 28, T_GRASS, 10, T_GRASS2, 2, T_GRASS, 28, T_GRASS2,
    40, T_GRASS, 40, T_GRASS2, 40, T_GRASS, 40, T_GRASS2,
    2, T_TREE_TL, 2, T_TREE_TR, 36, T_GRASS,
    2, T_TREE_BL, 2, T_TREE_BR, 36, T_GRASS2,
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_TOWN_NW (6) ── Main town, NW quarter — player starting area ───── */
static const uint8_t rle_town_nw[] = {
    /* Row 0: road at top */
    40, T_ROAD,
    /* Row 1: sidewalk */
    40, T_SIDEWALK,
    /* Rows 2-5: houses along top */
    2, T_SIDEWALK, 2, T_ROOF, 2, T_ROOF, 2, T_ROOF, 2, T_CHIMNEY, 8, T_SIDEWALK, 2, T_ROOF, 2, T_ROOF, 2, T_ROOF, 2, T_CHIMNEY, 8, T_SIDEWALK, 2, T_GRASS, 4, T_BUSH,
    2, T_SIDEWALK, 2, T_WALL_TOP, 2, T_WINDOW, 2, T_WALL_TOP, 2, T_WALL_TOP, 8, T_SIDEWALK, 2, T_WALL_TOP, 2, T_WINDOW, 2, T_WALL_TOP, 2, T_WALL_TOP, 8, T_SIDEWALK, 2, T_GRASS, 4, T_GRASS2,
    2, T_SIDEWALK, 2, T_WALL_SIDE, 2, T_WALL_SIDE, 2, T_DOOR_CLOSED, 2, T_WALL_SIDE, 8, T_SIDEWALK, 2, T_WALL_SIDE, 2, T_WALL_SIDE, 2, T_DOOR_CLOSED, 2, T_WALL_SIDE, 8, T_SIDEWALK, 2, T_GRASS2, 4, T_GRASS,
    2, T_SIDEWALK, 2, T_WALL_BOT, 2, T_WALL_BOT, 2, T_WALL_BOT, 2, T_WALL_BOT, 8, T_SIDEWALK, 2, T_WALL_BOT, 2, T_WALL_BOT, 2, T_WALL_BOT, 2, T_WALL_BOT, 8, T_SIDEWALK, 2, T_GRASS, 4, T_GRASS2,
    /* Row 6-7: sidewalk path area */
    20, T_SIDEWALK, 10, T_GRASS, 10, T_GRASS2,
    20, T_SIDEWALK, 10, T_GRASS2, 10, T_GRASS,
    /* Row 8-10: more houses */
    2, T_SIDEWALK, 2, T_ROOF, 2, T_ROOF, 2, T_ROOF, 2, T_ROOF, 8, T_SIDEWALK, 4, T_LAMP, 6, T_SIDEWALK, 4, T_GRASS, 6, T_GRASS2,
    2, T_SIDEWALK, 2, T_WALL_TOP, 2, T_WINDOW, 2, T_WINDOW, 2, T_WALL_TOP, 8, T_SIDEWALK, 4, T_SIDEWALK, 6, T_SIDEWALK, 4, T_GRASS2, 6, T_GRASS,
    2, T_SIDEWALK, 2, T_WALL_SIDE, 2, T_WALL_SIDE, 2, T_DOOR_CLOSED, 2, T_WALL_SIDE, 8, T_SIDEWALK, 4, T_SIDEWALK, 6, T_SIGN, 4, T_GRASS, 6, T_GRASS,
    /* Row 11-14: park / garden */
    4, T_SIDEWALK, 6, T_GRASS, 10, T_PATH_H, 10, T_GRASS, 10, T_GRASS2,
    4, T_GRASS, 6, T_GRASS2, 10, T_GRASS, 10, T_GRASS2, 10, T_GRASS,
    4, T_GRASS2, 4, T_FLOWER, 2, T_GRASS, 10, T_GRASS2, 10, T_GRASS, 10, T_GRASS2,
    4, T_GRASS, 6, T_GRASS, 10, T_GRASS, 10, T_GRASS2, 10, T_GRASS,
    /* Row 15-18: more town */
    40, T_SIDEWALK,
    40, T_ROAD,
    40, T_SIDEWALK,
    4, T_GRASS, 6, T_GRASS2, 10, T_SIDEWALK, 10, T_GRASS, 10, T_GRASS2,
    /* Row 19-24 */
    4, T_GRASS2, 6, T_GRASS, 10, T_SIDEWALK, 10, T_GRASS2, 10, T_GRASS,
    4, T_GRASS, 6, T_GRASS2, 10, T_SIDEWALK, 10, T_GRASS, 10, T_GRASS2,
    4, T_GRASS2, 4, T_BUSH, 2, T_GRASS, 10, T_SIDEWALK, 10, T_GRASS2, 10, T_GRASS,
    4, T_GRASS, 6, T_GRASS, 10, T_SIDEWALK, 10, T_GRASS, 10, T_GRASS2,
    4, T_GRASS2, 6, T_GRASS2, 10, T_SIDEWALK, 10, T_GRASS2, 10, T_GRASS,
    40, T_SIDEWALK,
    40, T_ROAD,
    40, T_SIDEWALK,
    /* HUD */
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_TOWN_NE (7) ── Town Hall + Shop area ──────────────────────────── */
static const uint8_t rle_town_ne[] = {
    40, T_ROAD,
    40, T_SIDEWALK,
    /* Town Hall facade */
    4, T_GRASS, 2, T_SIDEWALK, 4, T_ROOF, 4, T_ROOF, 4, T_ROOF, 4, T_CHIMNEY, 8, T_SIDEWALK, 10, T_GRASS,
    4, T_GRASS2, 2, T_SIDEWALK, 4, T_WALL_TOP, 4, T_WINDOW, 4, T_WALL_TOP, 4, T_WINDOW, 8, T_SIDEWALK, 10, T_GRASS2,
    4, T_GRASS, 2, T_SIDEWALK, 4, T_WALL_SIDE, 4, T_WALL_SIDE, 4, T_DOOR_CLOSED, 4, T_WALL_SIDE, 8, T_SIDEWALK, 10, T_GRASS,
    4, T_GRASS2, 2, T_SIDEWALK, 4, T_WALL_BOT, 4, T_WALL_BOT, 4, T_WALL_BOT, 4, T_WALL_BOT, 8, T_SIDEWALK, 10, T_GRASS2,
    /* Sidewalk + sign */
    4, T_GRASS, 2, T_SIGN, 18, T_SIDEWALK, 6, T_SIDEWALK, 10, T_GRASS,
    30, T_SIDEWALK, 10, T_GRASS2,
    /* Shop */
    4, T_GRASS, 2, T_SIDEWALK, 4, T_ROOF, 4, T_ROOF, 4, T_ROOF, 12, T_SIDEWALK, 10, T_GRASS,
    4, T_GRASS2, 2, T_SIDEWALK, 4, T_WALL_TOP, 4, T_WINDOW, 4, T_WALL_TOP, 12, T_SIDEWALK, 10, T_GRASS2,
    4, T_GRASS, 2, T_SIDEWALK, 4, T_WALL_SIDE, 4, T_DOOR_CLOSED, 4, T_WALL_SIDE, 12, T_SIDEWALK, 10, T_GRASS,
    4, T_GRASS2, 2, T_SIDEWALK, 4, T_WALL_BOT, 4, T_WALL_BOT, 4, T_WALL_BOT, 12, T_SIDEWALK, 10, T_GRASS2,
    /* Open area */
    4, T_GRASS, 16, T_SIDEWALK, 10, T_GRASS, 10, T_GRASS2,
    4, T_GRASS2, 16, T_SIDEWALK, 10, T_GRASS2, 10, T_GRASS,
    40, T_SIDEWALK,
    40, T_ROAD,
    40, T_SIDEWALK,
    20, T_GRASS, 10, T_SIDEWALK, 10, T_GRASS2,
    20, T_GRASS2, 10, T_SIDEWALK, 10, T_GRASS,
    20, T_GRASS, 10, T_SIDEWALK, 10, T_GRASS2,
    20, T_GRASS2, 10, T_SIDEWALK, 10, T_GRASS,
    4, T_GRASS, 4, T_FLOWER, 12, T_GRASS, 10, T_SIDEWALK, 10, T_GRASS2,
    4, T_GRASS2, 16, T_GRASS2, 10, T_SIDEWALK, 10, T_GRASS,
    40, T_SIDEWALK,
    40, T_ROAD,
    40, T_SIDEWALK,
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_MANSION_EAST (8) / SCR_LAKE_E (9) / SCR_PARK (10) — simplified ── */
static const uint8_t rle_generic_grass[] = {
    40, T_GRASS, 40, T_GRASS2, 40, T_GRASS, 40, T_GRASS2,
    40, T_GRASS, 40, T_GRASS2, 40, T_GRASS, 40, T_GRASS2,
    40, T_GRASS, 40, T_GRASS2, 40, T_GRASS, 40, T_GRASS2,
    40, T_GRASS, 40, T_GRASS2, 40, T_GRASS, 40, T_GRASS2,
    40, T_GRASS, 40, T_GRASS2, 40, T_GRASS, 40, T_GRASS2,
    40, T_GRASS, 40, T_GRASS2, 40, T_GRASS, 40, T_GRASS2,
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_TOWN_SW (11) ── Library area ───────────────────────────────────── */
static const uint8_t rle_town_sw[] = {
    40, T_SIDEWALK,
    40, T_ROAD,
    40, T_SIDEWALK,
    /* Library building */
    4, T_SIDEWALK, 4, T_ROOF, 4, T_ROOF, 4, T_ROOF, 4, T_ROOF, 12, T_SIDEWALK, 4, T_GRASS, 4, T_GRASS2,
    4, T_SIDEWALK, 4, T_WALL_TOP, 4, T_WINDOW, 4, T_WINDOW, 4, T_WALL_TOP, 12, T_SIDEWALK, 4, T_GRASS2, 4, T_GRASS,
    4, T_SIDEWALK, 4, T_WALL_SIDE, 4, T_WALL_SIDE, 4, T_DOOR_CLOSED, 4, T_WALL_SIDE, 12, T_SIDEWALK, 4, T_GRASS, 4, T_GRASS2,
    4, T_SIDEWALK, 4, T_WALL_BOT, 4, T_WALL_BOT, 4, T_WALL_BOT, 4, T_WALL_BOT, 12, T_SIDEWALK, 4, T_GRASS2, 4, T_GRASS,
    /* Open area */
    30, T_SIDEWALK, 4, T_GRASS, 6, T_GRASS2,
    30, T_SIDEWALK, 4, T_GRASS2, 6, T_GRASS,
    10, T_SIDEWALK, 4, T_LAMP, 16, T_SIDEWALK, 4, T_GRASS, 6, T_GRASS2,
    30, T_SIDEWALK, 4, T_GRASS2, 6, T_GRASS,
    /* Park area */
    10, T_GRASS, 4, T_FLOWER, 6, T_GRASS2, 10, T_GRASS, 4, T_BUSH, 6, T_GRASS2,
    10, T_GRASS2, 4, T_GRASS, 6, T_GRASS, 10, T_GRASS2, 4, T_GRASS, 6, T_GRASS,
    10, T_GRASS, 2, T_TREE_TL, 2, T_TREE_TR, 6, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    10, T_GRASS2, 2, T_TREE_BL, 2, T_TREE_BR, 6, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_TOWN_SE (12) ── Town SE corner ─────────────────────────────────── */
static const uint8_t rle_town_se[] = {
    40, T_SIDEWALK,
    40, T_ROAD,
    40, T_SIDEWALK,
    20, T_SIDEWALK, 10, T_GRASS, 10, T_GRASS2,
    20, T_SIDEWALK, 10, T_GRASS2, 10, T_GRASS,
    4, T_GRASS, 4, T_SIDEWALK, 12, T_SIDEWALK, 10, T_GRASS, 10, T_GRASS2,
    4, T_GRASS2, 4, T_SIDEWALK, 12, T_SIDEWALK, 10, T_GRASS2, 10, T_GRASS,
    20, T_SIDEWALK, 10, T_GRASS, 10, T_GRASS2,
    20, T_SIDEWALK, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_CAVE_ENTRY (15) ── Cave entrance in forest ────────────────────── */
static const uint8_t rle_cave_entry[] = {
    10, T_GRASS, 10, T_ROCK, 10, T_DARK_STONE, 10, T_GRASS,
    10, T_GRASS2, 10, T_ROCK, 10, T_DARK_STONE, 10, T_GRASS2,
    10, T_GRASS, 4, T_ROCK, 2, T_CAVE_WALL, 2, T_CAVE_WALL, 2, T_CAVE_WALL, 2, T_CAVE_WALL, 8, T_ROCK, 10, T_GRASS,
    10, T_GRASS2, 4, T_ROCK, 2, T_CAVE_WALL, 6, T_CAVE_FLOOR, 2, T_CAVE_WALL, 4, T_ROCK, 10, T_GRASS2,
    10, T_GRASS, 4, T_ROCK, 2, T_CAVE_WALL, 6, T_CAVE_FLOOR, 2, T_CAVE_WALL, 4, T_ROCK, 10, T_GRASS,
    10, T_GRASS2, 4, T_ROCK, 2, T_CAVE_WALL, 6, T_CAVE_FLOOR, 2, T_CAVE_WALL, 4, T_ROCK, 10, T_GRASS2,
    10, T_GRASS, 4, T_ROCK, 2, T_CAVE_WALL, 2, T_TORCH, 4, T_CAVE_FLOOR, 2, T_CAVE_WALL, 4, T_ROCK, 10, T_GRASS,
    10, T_GRASS2, 4, T_ROCK, 2, T_CAVE_WALL, 6, T_CAVE_FLOOR, 2, T_CAVE_WALL, 4, T_ROCK, 10, T_GRASS2,
    10, T_GRASS, 4, T_ROCK, 2, T_CAVE_WALL, 6, T_LADDER, 2, T_CAVE_WALL, 4, T_ROCK, 10, T_GRASS,
    10, T_GRASS2, 4, T_ROCK, 12, T_CAVE_WALL, 4, T_ROCK, 10, T_GRASS2,
    10, T_GRASS, 10, T_ROCK, 10, T_DARK_STONE, 10, T_GRASS,
    10, T_GRASS2, 10, T_ROCK, 10, T_DARK_STONE, 10, T_GRASS2,
    /* Forest around cave */
    2, T_TREE_TL, 2, T_TREE_TR, 16, T_GRASS, 10, T_GRASS, 10, T_GRASS2,
    2, T_TREE_BL, 2, T_TREE_BR, 16, T_GRASS2, 10, T_GRASS2, 10, T_GRASS,
    20, T_GRASS, 10, T_TALL_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    20, T_GRASS2, 10, T_GRASS2, 10, T_GRASS2,
    20, T_GRASS, 10, T_GRASS, 10, T_GRASS,
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_BEACH_W (16) ── Beach area ─────────────────────────────────────── */
static const uint8_t rle_beach_w[] = {
    20, T_GRASS, 20, T_SAND,
    20, T_GRASS2, 20, T_SAND,
    10, T_GRASS, 10, T_SAND, 20, T_WATER,
    10, T_GRASS2, 10, T_SAND, 20, T_WATER,
    10, T_GRASS, 10, T_SAND, 20, T_WATER,
    10, T_GRASS2, 10, T_SAND, 20, T_WATER_DEEP,
    10, T_GRASS, 10, T_SAND, 20, T_WATER,
    10, T_GRASS2, 10, T_SAND, 20, T_WATER,
    10, T_SAND, 10, T_SAND, 20, T_WATER,
    10, T_SAND, 10, T_SAND, 20, T_WATER_DEEP,
    10, T_SAND, 10, T_SAND, 20, T_WATER,
    10, T_SAND, 10, T_SAND, 20, T_WATER,
    10, T_SAND, 10, T_SAND, 20, T_WATER,
    10, T_SAND, 10, T_SAND, 20, T_WATER_DEEP,
    10, T_SAND, 10, T_SAND, 20, T_WATER,
    10, T_SAND, 10, T_SAND, 20, T_WATER,
    10, T_GRASS, 10, T_SAND, 20, T_WATER,
    10, T_GRASS2, 10, T_SAND, 20, T_WATER_DEEP,
    10, T_GRASS, 10, T_SAND, 20, T_WATER,
    10, T_GRASS2, 10, T_SAND, 20, T_WATER,
    20, T_GRASS, 20, T_SAND,
    20, T_GRASS2, 20, T_SAND,
    20, T_GRASS, 20, T_SAND,
    20, T_GRASS2, 20, T_SAND,
    20, T_GRASS, 20, T_SAND,
    40, T_GRASS, 40, T_GRASS, 40, T_GRASS,
};

/* ── SCR_DOCKS (18) ── Wooden docks ─────────────────────────────────────── */
static const uint8_t rle_docks[] = {
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 4, T_BRIDGE_H, 4, T_BRIDGE_H, 22, T_WATER,
    10, T_SAND, 4, T_BRIDGE_H, 4, T_BRIDGE_H, 22, T_WATER,
    10, T_SAND, 4, T_BRIDGE_H, 26, T_WATER,
    10, T_SAND, 4, T_BRIDGE_H, 26, T_WATER_DEEP,
    10, T_SAND, 4, T_BRIDGE_H, 26, T_WATER,
    10, T_SAND, 4, T_BRIDGE_H, 26, T_WATER,
    10, T_SAND, 4, T_BRIDGE_H, 26, T_WATER,
    10, T_SAND, 4, T_BRIDGE_H, 26, T_WATER_DEEP,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER_DEEP,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER_DEEP,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    10, T_SAND, 30, T_WATER,
    40, T_SAND, 40, T_SAND, 40, T_SAND,
};

/* ── Indoor screens ─── Simple rectangular rooms ───────────────────────── */

/* SCR_HOUSE_GROUND (21) — Player's house, ground floor */
static const uint8_t rle_house_ground[] = {
    40, T_WALL_TOP,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_CARPET, 10, T_WOOD_FLOOR, 2, T_TABLE, 2, T_TABLE, 2, T_CHAIR, 14, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_CARPET, 10, T_WOOD_FLOOR, 2, T_CHAIR, 2, T_WOOD_FLOOR, 2, T_WOOD_FLOOR, 14, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 2, T_FIREPLACE, 34, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 10, T_WOOD_FLOOR, 2, T_BOOKSHELF, 4, T_WOOD_FLOOR, 2, T_BOOKSHELF, 18, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 10, T_WOOD_FLOOR, 2, T_BED, 2, T_BED, 4, T_WOOD_FLOOR, 18, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 10, T_WOOD_FLOOR, 2, T_STAIRS_UP, 26, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 14, T_WOOD_FLOOR, 4, T_DOOR_OPEN, 18, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    40, T_WALL_BOT, 40, T_WALL_BOT, 40, T_WALL_BOT,
};

/* SCR_HOUSE_ATTIC (22) — Player's house, attic (diary found here) */
static const uint8_t rle_house_attic[] = {
    40, T_WALL_TOP,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_CRATE, 4, T_BARREL, 28, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_CRATE, 32, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 10, T_WOOD_FLOOR, 2, T_CHEST_CLOSED, 24, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_BARREL, 4, T_CRATE, 28, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 10, T_WOOD_FLOOR, 2, T_STAIRS_DOWN, 24, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    40, T_WALL_BOT, 40, T_WALL_BOT, 40, T_WALL_BOT,
};

/* SCR_TOWN_HALL (23) — inside the town hall */
static const uint8_t rle_town_hall[] = {
    40, T_WALL_TOP,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_BOOKSHELF, 8, T_CARPET, 4, T_TABLE, 4, T_CARPET, 4, T_BOOKSHELF, 8, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 14, T_CARPET, 4, T_DOOR_OPEN, 18, T_CARPET, 2, T_WALL_SIDE,
    40, T_WALL_BOT, 40, T_WALL_BOT, 40, T_WALL_BOT,
};

/* SCR_SHOP (24) — Ada's shop */
static const uint8_t rle_shop[] = {
    40, T_WALL_TOP,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_BARREL, 4, T_BARREL, 8, T_WOOD_FLOOR, 4, T_CRATE, 4, T_CRATE, 8, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 20, T_TABLE, 16, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 14, T_WOOD_FLOOR, 4, T_DOOR_OPEN, 18, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    40, T_WALL_BOT, 40, T_WALL_BOT, 40, T_WALL_BOT,
};

/* SCR_LIBRARY (25) — Whitmore's library */
static const uint8_t rle_library[] = {
    40, T_WALL_TOP,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_BOOKSHELF, 4, T_BOOKSHELF, 8, T_WOOD_FLOOR, 4, T_BOOKSHELF, 4, T_BOOKSHELF, 8, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 10, T_WOOD_FLOOR, 4, T_TABLE, 4, T_CHAIR, 18, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_BOOKSHELF, 32, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_BOOKSHELF, 4, T_BOOKSHELF, 28, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 14, T_WOOD_FLOOR, 4, T_DOOR_OPEN, 18, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    40, T_WALL_BOT, 40, T_WALL_BOT, 40, T_WALL_BOT,
};

/* SCR_OLD_CABIN (26) — Old Man's cabin */
static const uint8_t rle_old_cabin[] = {
    40, T_WALL_TOP,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 2, T_FIREPLACE, 34, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 10, T_WOOD_FLOOR, 2, T_TABLE, 24, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 10, T_WOOD_FLOOR, 2, T_CHAIR, 24, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_BOOKSHELF, 32, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 14, T_WOOD_FLOOR, 4, T_DOOR_OPEN, 18, T_WOOD_FLOOR, 2, T_WALL_SIDE,
    40, T_WALL_BOT, 40, T_WALL_BOT, 40, T_WALL_BOT,
};

/* SCR_MANSION_HALL (27) — Mansion main hall */
static const uint8_t rle_mansion_hall[] = {
    40, T_WALL_TOP,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_BOOKSHELF, 8, T_CARPET, 4, T_LAMP, 8, T_CARPET, 4, T_BOOKSHELF, 4, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 14, T_CARPET, 4, T_STAIRS_UP, 18, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_CARPET, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 14, T_CARPET, 4, T_DOOR_OPEN, 18, T_CARPET, 2, T_WALL_SIDE,
    40, T_WALL_BOT, 40, T_WALL_BOT, 40, T_WALL_BOT,
};

/* SCR_CAVE_INSIDE (30) — Inside cave */
static const uint8_t rle_cave_inside[] = {
    40, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 4, T_TORCH, 32, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 10, T_CAVE_FLOOR, 4, T_CRYSTAL, 22, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 4, T_TORCH, 8, T_CAVE_FLOOR, 2, T_CHEST_CLOSED, 22, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 14, T_CAVE_FLOOR, 2, T_LADDER, 20, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 14, T_CAVE_FLOOR, 2, T_LADDER, 20, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    40, T_CAVE_WALL, 40, T_CAVE_WALL, 40, T_CAVE_WALL,
};

/* SCR_ANOMALY_CHAMBER (32) — Final area with portal */
static const uint8_t rle_anomaly_chamber[] = {
    40, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 4, T_CRYSTAL, 8, T_CAVE_FLOOR, 4, T_ANOMALY_GROUND, 4, T_ANOMALY_GROUND, 8, T_CAVE_FLOOR, 4, T_CRYSTAL, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 10, T_CAVE_FLOOR, 4, T_GLOW_TILE, 4, T_GLOW_TILE, 4, T_GLOW_TILE, 14, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 14, T_CAVE_FLOOR, 4, T_PORTAL, 18, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 10, T_CAVE_FLOOR, 4, T_GLOW_TILE, 4, T_GLOW_TILE, 4, T_GLOW_TILE, 14, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 4, T_CRYSTAL, 8, T_CAVE_FLOOR, 4, T_ANOMALY_GROUND, 4, T_ANOMALY_GROUND, 8, T_CAVE_FLOOR, 4, T_CRYSTAL, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 36, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    2, T_CAVE_WALL, 14, T_CAVE_FLOOR, 2, T_LADDER, 20, T_CAVE_FLOOR, 2, T_CAVE_WALL,
    40, T_CAVE_WALL, 40, T_CAVE_WALL, 40, T_CAVE_WALL,
};

/* SCR_LAB (33) — Elara's secret lab */
static const uint8_t rle_lab[] = {
    40, T_WALL_TOP,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_TABLE, 8, T_STONE, 4, T_TABLE, 18, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 10, T_STONE, 4, T_ANOMALY_GROUND, 22, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 4, T_BOOKSHELF, 4, T_BOOKSHELF, 28, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 36, T_STONE, 2, T_WALL_SIDE,
    2, T_WALL_SIDE, 14, T_STONE, 4, T_DOOR_OPEN, 18, T_STONE, 2, T_WALL_SIDE,
    40, T_WALL_BOT, 40, T_WALL_BOT, 40, T_WALL_BOT,
};

/* ═══════════════════════════════════════════════════════════════════════════
 *  DOORS
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Town NW — player house door */
static const door_t doors_town_nw[] = {
    { 6, 4, SCR_HOUSE_GROUND, 18, 23, 0, ITEM_NONE },          /* left house */
    { 16, 4, SCR_SHOP, 18, 23, 0, ITEM_NONE },                 /* right house = shop alt entry */
    { 6, 10, SCR_HOUSE_GROUND, 18, 23, 0, ITEM_NONE },         /* bigger house */
};

/* Town NE — town hall and shop doors */
static const door_t doors_town_ne[] = {
    { 14, 4, SCR_TOWN_HALL, 18, 23, 0, ITEM_NONE },            /* town hall */
    { 14, 10, SCR_SHOP, 18, 23, 0, ITEM_NONE },                /* shop */
};

/* Town SW — library door */
static const door_t doors_town_sw[] = {
    { 14, 5, SCR_LIBRARY, 18, 23, 0, ITEM_NONE },              /* library */
};

/* Mansion ext — gate + main door */
static const door_t doors_mansion_ext[] = {
    { 18, 9, SCR_MANSION_HALL, 18, 23, 0, ITEM_MANSION_KEY },  /* gate needs key */
    { 14, 7, SCR_MANSION_HALL, 18, 23, 0, ITEM_MANSION_KEY },  /* mansion door needs key */
};

/* Cave entry — ladder into cave */
static const door_t doors_cave_entry[] = {
    { 18, 8, SCR_CAVE_INSIDE, 8, 1, 0, ITEM_NONE },           /* ladder */
};

/* House ground — exits & stairs */
static const door_t doors_house_ground[] = {
    { 18, 24, SCR_TOWN_NW, 7, 5, 0, ITEM_NONE },              /* exit to town */
    { 6, 16, SCR_HOUSE_ATTIC, 6, 12, 0, ITEM_NONE },          /* stairs up */
};

/* House attic — stairs down */
static const door_t doors_house_attic[] = {
    { 6, 12, SCR_HOUSE_GROUND, 6, 16, 0, ITEM_NONE },         /* stairs down */
};

/* Town hall — exit */
static const door_t doors_town_hall[] = {
    { 18, 24, SCR_TOWN_NE, 15, 5, 0, ITEM_NONE },
};

/* Shop — exit */
static const door_t doors_shop[] = {
    { 18, 24, SCR_TOWN_NE, 15, 11, 0, ITEM_NONE },
};

/* Library — exit */
static const door_t doors_library[] = {
    { 18, 24, SCR_TOWN_SW, 15, 6, 0, ITEM_NONE },
};

/* Old cabin — exit to forest */
static const door_t doors_old_cabin[] = {
    { 18, 24, SCR_FOREST_W, 20, 10, 0, ITEM_NONE },
};

/* Mansion hall — exit + upstairs */
static const door_t doors_mansion_hall[] = {
    { 18, 24, SCR_MANSION_EXT, 15, 8, 0, ITEM_NONE },
    { 9, 5, SCR_MANSION_STUDY, 18, 23, 0, ITEM_NONE },        /* stairs to study */
};

/* Cave inside — ladders */
static const door_t doors_cave_inside[] = {
    { 8, 16, SCR_CAVE_ENTRY, 18, 7, 0, ITEM_NONE },           /* exit ladder */
    { 8, 23, SCR_ANOMALY_CHAMBER, 8, 24, QF_HAS_LANTERN, ITEM_NONE },
};

/* Anomaly chamber — exit */
static const door_t doors_anomaly_chamber[] = {
    { 8, 24, SCR_CAVE_INSIDE, 8, 22, 0, ITEM_NONE },          /* back up */
};

/* Lab — exit */
static const door_t doors_lab[] = {
    { 18, 24, SCR_TOWN_SE, 20, 10, 0, ITEM_NONE },
};

/* ═══════════════════════════════════════════════════════════════════════════
 *  NPC SPAWNS
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Town NW — Tommy hangs out here */
static const npc_spawn_t npcs_town_nw[] = {
    { NPC_TOMMY, 20, 8, DIR_DOWN, 0, 0 },
};

/* Town NE — Mayor + Ada */
static const npc_spawn_t npcs_town_ne[] = {
    { NPC_MAYOR, 20, 6, DIR_DOWN, 0, 0 },
    { NPC_ADA, 25, 14, DIR_DOWN, 0, 0 },
};

/* Town SW — Pete near park */
static const npc_spawn_t npcs_town_sw[] = {
    { NPC_PETE, 15, 15, DIR_DOWN, 0, 0 },
};

/* Forest W — Old Man in forest */
static const npc_spawn_t npcs_forest_w[] = {
    { NPC_OLD_MAN, 20, 12, DIR_DOWN, 0, 0 },
};

/* Town hall — Mayor inside */
static const npc_spawn_t npcs_town_hall[] = {
    { NPC_MAYOR, 20, 8, DIR_DOWN, 0, 0 },
};

/* Shop — Ada inside */
static const npc_spawn_t npcs_shop[] = {
    { NPC_ADA, 20, 8, DIR_DOWN, 0, 0 },
};

/* Library — Whitmore */
static const npc_spawn_t npcs_library[] = {
    { NPC_WHITMORE, 20, 8, DIR_DOWN, 0, 0 },
};

/* Old cabin — Old Man */
static const npc_spawn_t npcs_old_cabin[] = {
    { NPC_OLD_MAN, 15, 8, DIR_DOWN, 0, 0 },
};

/* Lab — Elara */
static const npc_spawn_t npcs_lab[] = {
    { NPC_ELARA, 15, 8, DIR_DOWN, 0, 0 },
};

/* Anomaly chamber — Ghost appears after all crystals */
static const npc_spawn_t npcs_anomaly_chamber[] = {
    { NPC_GHOST, 18, 10, DIR_DOWN, QF_CRYSTAL_1 | QF_CRYSTAL_2 | QF_CRYSTAL_3, 0 },
};

/* ═══════════════════════════════════════════════════════════════════════════
 *  ITEM SPAWNS
 * ═══════════════════════════════════════════════════════════════════════════ */

/* House attic — diary */
static const item_spawn_t items_house_attic[] = {
    { ITEM_DIARY, 6, 5, QF_HAS_DIARY },
};

/* Forest NW — lantern */
static const item_spawn_t items_forest_nw[] = {
    { ITEM_LANTERN, 10, 10, QF_HAS_LANTERN },
};

/* Cave inside — crystal + compass */
static const item_spawn_t items_cave_inside[] = {
    { ITEM_CRYSTAL_1, 7, 6, QF_CRYSTAL_1 },
    { ITEM_COMPASS, 20, 10, QF_HAS_COMPASS },
};

/* Beach — tackle box */
static const item_spawn_t items_beach_w[] = {
    { ITEM_TACKLE_BOX, 12, 10, QF_PETE_QUEST_DONE },
};

/* Mansion hall — mansion key + crystal */
static const item_spawn_t items_mansion_hall[] = {
    { ITEM_CRYSTAL_2, 30, 6, QF_CRYSTAL_2 },
};

/* Lab — crystal + keycard */
static const item_spawn_t items_lab[] = {
    { ITEM_CRYSTAL_3, 20, 6, QF_CRYSTAL_3 },
    { ITEM_LAB_KEYCARD, 10, 4, QF_HAS_KEYCARD },
};

/* Forest NE — diary page */
static const item_spawn_t items_forest_ne[] = {
    { ITEM_DIARY_PAGE, 15, 10, 0 },
};

/* ═══════════════════════════════════════════════════════════════════════════
 *  SCREEN DEFINITION TABLE
 * ═══════════════════════════════════════════════════════════════════════════ */
#define S(rle) rle, sizeof(rle)
#define NO_CONN {-1,-1,-1,-1}
#define NDOORS(d) d, (sizeof(d)/sizeof(d[0]))
#define NNPCS(n) n, (sizeof(n)/sizeof(n[0]))
#define NITEMS(i) i, (sizeof(i)/sizeof(i[0]))
#define NO_DOORS  0, 0
#define NO_NPCS   0, 0
#define NO_ITEMS  0, 0

const screen_def_t world_screens[NUM_SCREENS] = {
    /* 0  SCR_FOREST_NW */
    { S(rle_forest_nw),  {-1, SCR_FOREST_W, -1, SCR_FOREST_N},
      NO_DOORS, NO_NPCS,
      NITEMS(items_forest_nw) },

    /* 1  SCR_FOREST_N */
    { S(rle_forest_n),   {-1, SCR_TOWN_NW, SCR_FOREST_NW, SCR_FOREST_NE},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 2  SCR_FOREST_NE */
    { S(rle_forest_ne),  {-1, SCR_MANSION_EAST, SCR_FOREST_N, -1},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0,
      NITEMS(items_forest_ne) },

    /* 3  SCR_MANSION_EXT */
    { S(rle_mansion_ext), {-1, -1, -1, SCR_MANSION_EAST},
      NDOORS(doors_mansion_ext), (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 4  SCR_LAKE_W */
    { S(rle_lake_w),     {SCR_FOREST_NW, SCR_BEACH_W, -1, SCR_LAKE_E},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 5  SCR_FOREST_W */
    { S(rle_forest_w),   {SCR_FOREST_NW, SCR_PARK, -1, SCR_TOWN_NW},
      (const door_t*)0, 0, NNPCS(npcs_forest_w), (const item_spawn_t*)0, 0 },

    /* 6  SCR_TOWN_NW — starting area */
    { S(rle_town_nw),    {SCR_FOREST_N, SCR_TOWN_SW, SCR_FOREST_W, SCR_TOWN_NE},
      NDOORS(doors_town_nw), NNPCS(npcs_town_nw), (const item_spawn_t*)0, 0 },

    /* 7  SCR_TOWN_NE */
    { S(rle_town_ne),    {SCR_FOREST_N, SCR_TOWN_SE, SCR_TOWN_NW, SCR_MANSION_EAST},
      NDOORS(doors_town_ne), NNPCS(npcs_town_ne), (const item_spawn_t*)0, 0 },

    /* 8  SCR_MANSION_EAST */
    { S(rle_generic_grass), {SCR_FOREST_NE, SCR_FOREST_PATH, SCR_TOWN_NE, SCR_MANSION_EXT},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 9  SCR_LAKE_E */
    { S(rle_generic_grass), {-1, -1, SCR_LAKE_W, -1},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 10 SCR_PARK */
    { S(rle_generic_grass), {SCR_FOREST_W, SCR_CAVE_ENTRY, -1, SCR_TOWN_SW},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 11 SCR_TOWN_SW */
    { S(rle_town_sw),    {SCR_TOWN_NW, SCR_BEACH_W, SCR_PARK, SCR_TOWN_SE},
      NDOORS(doors_town_sw), NNPCS(npcs_town_sw), (const item_spawn_t*)0, 0 },

    /* 12 SCR_TOWN_SE */
    { S(rle_town_se),    {SCR_TOWN_NE, SCR_BEACH_E, SCR_TOWN_SW, SCR_FOREST_PATH},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 13 SCR_FOREST_PATH */
    { S(rle_generic_grass), {SCR_MANSION_EAST, SCR_FOREST_DEEP, SCR_TOWN_SE, -1},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 14 SCR_FOREST_DEEP */
    { S(rle_generic_grass), {SCR_FOREST_PATH, -1, SCR_CAVE_ENTRY, -1},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 15 SCR_CAVE_ENTRY */
    { S(rle_cave_entry), {SCR_PARK, SCR_FOREST_DEEP, -1, -1},
      NDOORS(doors_cave_entry), (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 16 SCR_BEACH_W */
    { S(rle_beach_w),    {SCR_TOWN_SW, -1, SCR_LAKE_W, SCR_BEACH_E},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, NITEMS(items_beach_w) },

    /* 17 SCR_BEACH_E */
    { S(rle_generic_grass), {SCR_TOWN_SE, -1, SCR_BEACH_W, SCR_DOCKS},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 18 SCR_DOCKS */
    { S(rle_docks),      {-1, -1, SCR_BEACH_E, -1},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 19 SCR_BEACH_COVE */
    { S(rle_generic_grass), {-1, -1, -1, -1},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 20 SCR_CLIFFS */
    { S(rle_generic_grass), {-1, -1, -1, -1},
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 21 SCR_HOUSE_GROUND */
    { S(rle_house_ground), NO_CONN,
      NDOORS(doors_house_ground), (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 22 SCR_HOUSE_ATTIC */
    { S(rle_house_attic), NO_CONN,
      NDOORS(doors_house_attic), (const npc_spawn_t*)0, 0, NITEMS(items_house_attic) },

    /* 23 SCR_TOWN_HALL */
    { S(rle_town_hall),  NO_CONN,
      NDOORS(doors_town_hall), NNPCS(npcs_town_hall), (const item_spawn_t*)0, 0 },

    /* 24 SCR_SHOP */
    { S(rle_shop),       NO_CONN,
      NDOORS(doors_shop), NNPCS(npcs_shop), (const item_spawn_t*)0, 0 },

    /* 25 SCR_LIBRARY */
    { S(rle_library),    NO_CONN,
      NDOORS(doors_library), NNPCS(npcs_library), (const item_spawn_t*)0, 0 },

    /* 26 SCR_OLD_CABIN */
    { S(rle_old_cabin),  NO_CONN,
      NDOORS(doors_old_cabin), NNPCS(npcs_old_cabin), (const item_spawn_t*)0, 0 },

    /* 27 SCR_MANSION_HALL */
    { S(rle_mansion_hall), NO_CONN,
      NDOORS(doors_mansion_hall), (const npc_spawn_t*)0, 0, NITEMS(items_mansion_hall) },

    /* 28 SCR_MANSION_STUDY */
    { S(rle_generic_grass), NO_CONN,
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 29 SCR_MANSION_BASEMENT */
    { S(rle_generic_grass), NO_CONN,
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 30 SCR_CAVE_INSIDE */
    { S(rle_cave_inside), NO_CONN,
      NDOORS(doors_cave_inside), (const npc_spawn_t*)0, 0, NITEMS(items_cave_inside) },

    /* 31 SCR_CAVE_PASSAGES */
    { S(rle_generic_grass), NO_CONN,
      (const door_t*)0, 0, (const npc_spawn_t*)0, 0, (const item_spawn_t*)0, 0 },

    /* 32 SCR_ANOMALY_CHAMBER */
    { S(rle_anomaly_chamber), NO_CONN,
      NDOORS(doors_anomaly_chamber), NNPCS(npcs_anomaly_chamber), (const item_spawn_t*)0, 0 },

    /* 33 SCR_LAB */
    { S(rle_lab),        NO_CONN,
      NDOORS(doors_lab), NNPCS(npcs_lab), NITEMS(items_lab) },
};

/* ═══════════════════════════════════════════════════════════════════════════
 *  World functions
 * ═══════════════════════════════════════════════════════════════════════════ */

void world_load_screen(int screen_id) {
    if (screen_id < 0 || screen_id >= NUM_SCREENS) return;
    current_screen_id = (uint8_t)screen_id;
    const screen_def_t *scr = &world_screens[screen_id];
    rle_decode(scr->rle_data, scr->rle_size, current_tiles, TILES_X * TILES_Y);
}

int world_get_tile(int tx, int ty) {
    if (tx < 0 || tx >= TILES_X || ty < 0 || ty >= MAP_TILES_Y)
        return T_WALL_TOP; /* out of bounds = solid */
    return current_tiles[ty * TILES_X + tx];
}

const door_t *world_find_door(int tile_x, int tile_y) {
    const screen_def_t *scr = &world_screens[current_screen_id];
    for (int i = 0; i < scr->num_doors; i++) {
        if (scr->doors[i].tile_x == tile_x && scr->doors[i].tile_y == tile_y)
            return &scr->doors[i];
    }
    return 0;
}

const npc_spawn_t *world_get_npc_spawns(int *count) {
    const screen_def_t *scr = &world_screens[current_screen_id];
    *count = scr->num_npcs;
    return scr->npc_spawns;
}

const item_spawn_t *world_get_item_spawns(int *count) {
    const screen_def_t *scr = &world_screens[current_screen_id];
    *count = scr->num_items;
    return scr->item_spawns;
}
