/**
 * @file main.c
 * @brief AkiraOS NES emulator — app entry point
 *
 * Reads NES buttons from the akiraconsole DPAD GPIOs, runs the NES
 * machine, and pushes each frame to the AkiraOS display via
 * display_bitmap().  The NES 256×240 image is centered on the
 * 320×240 display with 32-pixel black bars on left and right.
 *
 * ROM data is supplied by rom_data.c (generated by rom_to_wasm.py):
 *   const uint8_t  rom_data[];
 *   const uint32_t rom_size;
 *
 * Button mapping (akiraconsole pins):
 *   D-pad Up    (pin  4) → NES Up
 *   D-pad Down  (pin  5) → NES Down
 *   D-pad Left  (pin  6) → NES Left
 *   D-pad Right (pin  7) → NES Right
 *   A button    (pin 15) → NES A
 *   B button    (pin 16) → NES B
 *   Y button    (pin 41) → NES Start
 *   X button    (pin 17) → NES Select
 *   Settings    (pin  2) → Pause menu only (not sent to NES)
 *
 * @license Apache-2.0
 */
#include "akira_api.h"
#include "nes.h"

/* ── ROM data (generated by rom_to_wasm.py) ─────────────────────────── */
extern const uint8_t  rom_data[];
extern const uint32_t rom_size;

/* ── Display geometry ────────────────────────────────────────────────── */
#define DISP_W       320
#define DISP_H       240
#define NES_OFFSET_X ((DISP_W - NES_W) / 2)   /* 32 px left margin */
#define NES_OFFSET_Y 0

/* ── GPIO pin assignments (akiraconsole) ─────────────────────────────── */
#define PIN_UP        4
#define PIN_DOWN      5
#define PIN_LEFT      6
#define PIN_RIGHT     7
#define PIN_A        15
#define PIN_B        16
#define PIN_SETTINGS  2
#define PIN_X        17
#define PIN_Y        41

/* ── Pause menu ──────────────────────────────────────────────────────── */
#define MENU_RESUME   0
#define MENU_RESTART  1
#define MENU_EXIT     2
#define MENU_COUNT    3

static const char *MENU_LABELS[MENU_COUNT] = {
    "[ Resume Game ]",
    "[Restart Game ]",
    "[Exit to Menu ]",
};

/* Returns MENU_RESUME / MENU_RESTART / MENU_EXIT */
static int show_pause_menu(void)
{
    /* Wait for Settings button release */
    while (gpio_read(PIN_SETTINGS)) delay(10000);
    delay(50000);

    int cur = 0;
    int redraw = 1;
    int prev_s = 0, prev_u = 0, prev_d = 0, prev_a = 0, prev_b = 0;

    const int ITEM_H = 22;
    const int PAD    = 6;
    const int mw     = 130;
    const int mh     = PAD + 16 + MENU_COUNT * ITEM_H + PAD;
    const int mx     = (DISP_W - mw) / 2;
    const int my     = (DISP_H - mh) / 2;

    while (1) {
        if (redraw) {
            display_rect(mx - 2, my - 2, mw + 4, mh + 4, 0x4A69);
            display_rect(mx, my, mw, mh, 0x0821);
            display_text(mx + PAD, my + PAD, "PAUSED", 0x07FF);
            for (int i = 0; i < MENU_COUNT; i++) {
                int iy  = my + PAD + 18 + i * ITEM_H;
                uint32_t bg = (i == cur) ? 0x001F : 0x0821;
                uint32_t fg = (i == cur) ? 0xFFFF : 0xC618;
                display_rect(mx, iy - 2, mw, ITEM_H - 2, bg);
                display_text(mx + PAD, iy, MENU_LABELS[i], fg);
            }
            display_flush();
            redraw = 0;
        }

        int s = gpio_read(PIN_SETTINGS);
        int u = gpio_read(PIN_UP);
        int d = gpio_read(PIN_DOWN);
        int a = gpio_read(PIN_A);
        int b = gpio_read(PIN_B);

        if (s && !prev_s)              return MENU_RESUME;
        if (u && !prev_u) { cur = (cur > 0) ? cur - 1 : MENU_COUNT - 1; redraw = 1; }
        if (d && !prev_d) { cur = (cur < MENU_COUNT - 1) ? cur + 1 : 0; redraw = 1; }
        if ((a && !prev_a) || (b && !prev_b)) return cur;

        prev_s = s; prev_u = u; prev_d = d; prev_a = a; prev_b = b;
        delay(20000);
    }
}

/* ── GPIO setup ──────────────────────────────────────────────────────── */
static void init_gpio(void)
{
    int flags = GPIO_INPUT | GPIO_PULL_DOWN;
    gpio_configure(PIN_UP,       flags);
    gpio_configure(PIN_DOWN,     flags);
    gpio_configure(PIN_LEFT,     flags);
    gpio_configure(PIN_RIGHT,    flags);
    gpio_configure(PIN_A,        flags);
    gpio_configure(PIN_B,        flags);
    gpio_configure(PIN_SETTINGS, flags);
    gpio_configure(PIN_X,        flags);
    gpio_configure(PIN_Y,        flags);
}

/* ── NES machine (static: avoids stack overflow) ─────────────────────── */
static NES nes;

/* ── Main ────────────────────────────────────────────────────────────── */
int main(void)
{
    printf("AkiraOS NES Emulator");

    init_gpio();

    /* Draw loading screen — use symmetric colors (0x0000/0xFFFF) so they
     * appear correctly regardless of SPI byte order.                     */
    display_clear(0x0000);
    display_text_large(80, 100, "NES", 0xFFFF);
    display_text_large(140, 100, "EMULATOR", 0xFFFF);
    display_text(90, 140, "Loading ROM...", 0xFFFF);
    display_flush();

    /* Initialise NES with bundled ROM */
    if (nes_init(&nes, rom_data, rom_size) != 0) {
        display_clear(0x0000);
        display_text(60, 100, "ERROR: Unsupported mapper!", 0xF800);
        display_text(60, 120, "Mappers 0,1,2,3,4,7,9,66,206 OK", 0xFFFF);
        display_flush();
        delay(4000000);
        app_switch("supervisor");
        return 1;
    }

    /* Black side bars (32 px each side) */
    display_rect(0,           0, NES_OFFSET_X, DISP_H, 0x0000);
    display_rect(NES_OFFSET_X + NES_W, 0, NES_OFFSET_X, DISP_H, 0x0000);
    display_flush();

    int settings_held = 0;
    int frame_count = 0;

    printf("[NES] Init OK — entering main loop\n");

    while (1) {
        /* ── Read input ─────────────────────────────────────────────── */
        uint8_t btns = 0;
        if (gpio_read(PIN_RIGHT))    btns |= NES_BTN_RIGHT;
        if (gpio_read(PIN_LEFT))     btns |= NES_BTN_LEFT;
        if (gpio_read(PIN_DOWN))     btns |= NES_BTN_DOWN;
        if (gpio_read(PIN_UP))       btns |= NES_BTN_UP;
        if (gpio_read(PIN_A))        btns |= NES_BTN_A;
        if (gpio_read(PIN_B))        btns |= NES_BTN_B;
        if (gpio_read(PIN_X))        btns |= NES_BTN_SELECT;
        if (gpio_read(PIN_Y))        btns |= NES_BTN_START;

        nes_set_controller(&nes, 0, btns);

        /* ── Check for pause (Settings button rising edge) ──────────── */
        int settings_now = gpio_read(PIN_SETTINGS);
        if (settings_now && !settings_held) {
            int choice = show_pause_menu();
            if (choice == MENU_EXIT) {
                app_switch("supervisor");
                return 0;
            }
            if (choice == MENU_RESTART) {
                nes_init(&nes, rom_data, rom_size);
                display_clear(0x0000);
                display_rect(0, 0, NES_OFFSET_X, DISP_H, 0x0000);
                display_rect(NES_OFFSET_X + NES_W, 0, NES_OFFSET_X, DISP_H, 0x0000);
                display_flush();
                frame_count = 0;
                printf("[NES] Restarted\n");
            }
            settings_held = 0;
            continue;
        }
        settings_held = settings_now;

        /* ── Run one NES frame ──────────────────────────────────────── */
        int skip = (frame_count % 4) != 0;  /* render 1 of 4 frames (~15fps) */
        nes.ppu.skip_render = (uint8_t)skip;
        nes_step_frame(&nes);
        frame_count++;

        /* ── Display output (skip 3 of 4 frames for ~4× speed) ───── */
        if (!skip) {
            display_bitmap(NES_OFFSET_X, NES_OFFSET_Y,
                           NES_W, NES_H,
                           nes.fb, NES_FB_BYTES);
            display_flush();
        }
        //delay(0);  // Disabled: frameskip already controls speed; kept for optional timing tuning.
    }

    return 0;
}
