/**
 * @file nes.h
 * @brief NES machine top-level for AkiraOS retro emulator
 *
 * Ties together the CPU, PPU, and mapper into a complete NES machine.
 *
 * External ROM data is supplied by rom_data.c (generated by rom_to_wasm.py):
 *   extern const uint8_t  rom_data[];
 *   extern const uint32_t rom_size;
 *
 * @license Apache-2.0
 */
#pragma once
#include <stdint.h>
#include "cpu6502.h"
#include "ppu.h"
#include "mapper.h"

/* ── NES controller button bitmask ─────────────────────────────────── *
 * The shift register at $4016/$4017 is read MSB-first: the FIRST read
 * returns bit 7, the SECOND bit 6, etc.  Button order as per NES spec:
 *   read 1=A  2=B  3=Select  4=Start  5=Up  6=Down  7=Left  8=Right
 * So A must live in bit 7, Right in bit 0.                             */
#define NES_BTN_A      0x80
#define NES_BTN_B      0x40
#define NES_BTN_SELECT 0x20
#define NES_BTN_START  0x10
#define NES_BTN_UP     0x08
#define NES_BTN_DOWN   0x04
#define NES_BTN_LEFT   0x02
#define NES_BTN_RIGHT  0x01

/* ── RGB565 framebuffer size ────────────────────────────────────────── */
#define NES_FB_PIXELS  (NES_W * NES_H)
#define NES_FB_BYTES   (NES_FB_PIXELS * 2)

typedef struct {
    CPU6502  cpu;
    PPU      ppu;
    Mapper   mapper;

    uint8_t  wram[2048];    /**< 2KB CPU work RAM                  */

    /* Controller shift registers */
    uint8_t  ctrl_latch;    /**< 1 while $4016 strobe is high      */
    uint8_t  ctrl_shift[2]; /**< Shift register for each controller*/
    uint8_t  ctrl_state[2]; /**< Latched button state              */

    /* RGB565 output frame buffer (NES_W × NES_H) */
    uint16_t fb[NES_FB_PIXELS];

    /* Set non-zero to request a clean exit */
    int      quit;

    /* OAM DMA stall: set to 513 when $4014 is written so nes_step_frame
     * feeds the missing PPU dots on the NEXT cpu6502_step call.         */
    int      dma_stall;
} NES;

/**
 * Initialise the NES machine.
 * @param nes      Machine state to initialise.
 * @param rom      Full iNES ROM image (must stay valid for the lifetime of nes).
 * @param rom_size Size of ROM image in bytes.
 * @return 0 on success, -1 on unsupported mapper.
 */
int  nes_init(NES *nes, const uint8_t *rom, uint32_t rom_size);

/**
 * Set controller button state.
 * @param nes    Machine.
 * @param port   Controller port (0 or 1).
 * @param mask   Bitmask of currently held buttons (NES_BTN_* flags OR'd).
 */
void nes_set_controller(NES *nes, int port, uint8_t mask);

/**
 * Run the NES until exactly one video frame is complete.
 * Renders to nes->fb (RGB565, NES_W×NES_H).
 */
void nes_step_frame(NES *nes);
