/**
 * @file main.c
 * @brief AkiraOS Game Boy / Game Boy Color emulator — app entry point
 *
 * Reads buttons from AkiraConsole GPIO pins, runs the GB/GBC machine,
 * and pushes each frame to the AkiraOS display via display_bitmap().
 *
 * The GB 160×144 image is centered on the 320×240 AkiraOS display:
 *   Horizontal offset: (320 - 160) / 2 = 80 px
 *   Vertical offset:   (240 - 144) / 2 = 48 px
 *
 * ROM data is supplied by rom_data.c (generated by rom_to_wasm.py):
 *   const uint8_t  rom_data[];
 *   const uint32_t rom_size;
 *
 * Button mapping (AkiraConsole pins):
 *   D-pad Up    (pin  4) → GB Up
 *   D-pad Down  (pin  5) → GB Down
 *   D-pad Left  (pin  6) → GB Left
 *   D-pad Right (pin  7) → GB Right
 *   A button    (pin 15) → GB A
 *   B button    (pin 16) → GB B
 *   X button    (pin 17) → GB Select
 *   Y button    (pin 41) → GB Start
 *   Settings    (pin  2) → Emulator pause menu
 *
 * @license Apache-2.0
 */
#include "akira_api.h"
#include "gb.h"

/* ── ROM data (generated by rom_to_wasm.py) ─────────────────────────── */
extern const uint8_t  rom_data[];
extern const uint32_t rom_size;

/* ── Display geometry ────────────────────────────────────────────────── */
#define DISP_W        320
#define DISP_H        240
#define GB_OFFSET_X   ((DISP_W - GB_W) / 2)    /* 80 px */
#define GB_OFFSET_Y   ((DISP_H - GB_H) / 2)    /* 48 px */

/* ── Frameskip ───────────────────────────────────────────────────────── */
static const int FS_MOD[4] = {1, 2, 3, 4};  /* 60 / 30 / 20 / 15 fps */
static int g_frameskip = 1;                  /* default: 30 fps (every other frame) */

/* ── GPIO pin assignments ────────────────────────────────────────────── */
#define PIN_UP        4
#define PIN_DOWN      5
#define PIN_LEFT      6
#define PIN_RIGHT     7
#define PIN_A        15
#define PIN_B        16
#define PIN_X        17
#define PIN_Y        41
#define PIN_SETTINGS  2

/* ── Pause menu ──────────────────────────────────────────────────────── */
#define MENU_RESUME   0
#define MENU_SETTINGS 1
#define MENU_RESTART  2
#define MENU_EXIT     3
#define MENU_COUNT    4

static const char *MENU_LABELS[MENU_COUNT] = {
    "[ Resume Game ]",
    "[Settings...  ]",
    "[Restart Game ]",
    "[Exit to Menu ]",
};

/* ── Tiny string helpers ─────────────────────────────────────────────── */
static int satoi(const char *s)
{
    int v = 0;
    while (*s >= '0' && *s <= '9') v = v * 10 + (*s++ - '0');
    return v;
}
static void sitoa(int v, char *b, int max)
{
    if (v == 0) { b[0]='0'; b[1]='\0'; return; }
    char t[8]; int ti=0, i=0;
    while (v>0 && ti<7) { t[ti++]='0'+v%10; v/=10; }
    while (ti-->0 && i<max-1) b[i++]=t[ti];
    b[i]='\0';
}

/* ── Settings persistence ────────────────────────────────────────────── */
static void load_settings(void)
{
    char buf[8];
    if (settings_get("gb/frameskip", buf, sizeof(buf)) == 0) {
        g_frameskip = satoi(buf);
        if (g_frameskip < 0) g_frameskip = 0;
        if (g_frameskip > 3) g_frameskip = 3;
    }
}
static void save_int(const char *key, int val)
{
    char buf[8];
    sitoa(val, buf, sizeof(buf));
    settings_set(key, buf);
}

/* ── Settings sub-menu ────────────────────────────────────────────────── */
static void show_settings_menu(void)
{
    static const char *FS_LABELS[4] = {
        "Off (60fps)", "Half (30fps)", "1/3 (20fps)", "1/4 (15fps)"
    };
    const int ITEM_H = 22;
    const int PAD    = 6;
    const int mw     = 160;
    const int mh     = PAD + 16 + 2 * ITEM_H + PAD;  /* Frameskip + Back */
    const int mx     = (DISP_W - mw) / 2;
    const int my     = (DISP_H - mh) / 2;

    int cur=0, dirty=1;
    int pu=0, pd=0, pa=0, pb=0, pl=0, pr=0;

    while (1) {
        if (dirty) {
            display_rect(mx-2, my-2, mw+4, mh+4, 0x4A69);
            display_rect(mx,   my,   mw,   mh,   0x0821);
            display_text(mx + PAD, my + PAD, "Settings", 0x07FF);
            /* Frameskip row */
            int iy0 = my + PAD + 18;
            uint32_t bg0 = (cur==0) ? 0x001F : 0x0821;
            uint32_t fg0 = (cur==0) ? 0xFFFF : 0xC618;
            display_rect(mx, iy0 - 2, mw, ITEM_H - 2, bg0);
            display_text(mx + PAD,      iy0, "Frame Skip",           fg0);
            display_text(mx + mw - 84,  iy0, FS_LABELS[g_frameskip], fg0);
            /* Back row */
            int iy1 = iy0 + ITEM_H;
            uint32_t bg1 = (cur==1) ? 0x001F : 0x0821;
            uint32_t fg1 = (cur==1) ? 0xFFFF : 0xC618;
            display_rect(mx, iy1 - 2, mw, ITEM_H - 2, bg1);
            display_text(mx + PAD, iy1, "Back", fg1);
            display_flush();
            dirty = 0;
        }
        int u=gpio_read(PIN_UP), d=gpio_read(PIN_DOWN);
        int a=gpio_read(PIN_A),  b=gpio_read(PIN_B);
        int l=gpio_read(PIN_LEFT),r=gpio_read(PIN_RIGHT);

        if (u&&!pu) { cur=(cur+1)%2; dirty=1; }
        if (d&&!pd) { cur=(cur+1)%2; dirty=1; }
        if ((l&&!pl)||(r&&!pr)) {
            if (cur == 0) {
                g_frameskip = (g_frameskip + ((r&&!pr)?1:-1) + 4) % 4;
                save_int("gb/frameskip", g_frameskip);
                dirty = 1;
            }
        }
        if (a&&!pa) {
            if (cur==0) { g_frameskip=(g_frameskip+1)%4; save_int("gb/frameskip",g_frameskip); dirty=1; }
            else break;
        }
        if (b&&!pb) break;
        pu=u; pd=d; pa=a; pb=b; pl=l; pr=r;
        delay(20000);
    }
}

static int show_pause_menu(void)
{
    while (gpio_read(PIN_SETTINGS)) delay(10000);
    delay(50000);

    int cur = 0, redraw = 1;
    int prev_s = 0, prev_u = 0, prev_d = 0, prev_a = 0, prev_b = 0;

    const int ITEM_H = 22;
    const int PAD    = 6;
    const int mw     = 130;
    const int mh     = PAD + 16 + MENU_COUNT * ITEM_H + PAD;
    const int mx     = (DISP_W - mw) / 2;
    const int my     = (DISP_H - mh) / 2;

    while (1) {
        if (redraw) {
            display_rect(mx - 2, my - 2, mw + 4, mh + 4, 0x4A69);
            display_rect(mx, my, mw, mh, 0x0821);
            display_text(mx + PAD, my + PAD, "PAUSED", 0x07FF);
            for (int i = 0; i < MENU_COUNT; i++) {
                int     iy = my + PAD + 18 + i * ITEM_H;
                uint32_t bg = (i == cur) ? 0x001F : 0x0821;
                uint32_t fg = (i == cur) ? 0xFFFF : 0xC618;
                display_rect(mx, iy - 2, mw, ITEM_H - 2, bg);
                display_text(mx + PAD, iy, MENU_LABELS[i], fg);
            }
            display_flush();
            redraw = 0;
        }

        int s = gpio_read(PIN_SETTINGS);
        int u = gpio_read(PIN_UP);
        int d = gpio_read(PIN_DOWN);
        int a = gpio_read(PIN_A);
        int b = gpio_read(PIN_B);

        if (s && !prev_s)              return MENU_RESUME;
        if (u && !prev_u) { cur = (cur > 0) ? cur - 1 : MENU_COUNT - 1; redraw = 1; }
        if (d && !prev_d) { cur = (cur < MENU_COUNT - 1) ? cur + 1 : 0; redraw = 1; }
        if (a && !prev_a) {
            if (cur == MENU_SETTINGS) { show_settings_menu(); redraw = 1; }
            else return cur;
        }
        if (b && !prev_b) return MENU_RESUME;

        prev_s = s; prev_u = u; prev_d = d; prev_a = a; prev_b = b;
        delay(20000);
    }
}

/* ── GPIO setup ──────────────────────────────────────────────────────── */
static void init_gpio(void)
{
    int flags = GPIO_INPUT | GPIO_PULL_DOWN;
    gpio_configure(PIN_UP,       flags);
    gpio_configure(PIN_DOWN,     flags);
    gpio_configure(PIN_LEFT,     flags);
    gpio_configure(PIN_RIGHT,    flags);
    gpio_configure(PIN_A,        flags);
    gpio_configure(PIN_B,        flags);
    gpio_configure(PIN_X,        flags);
    gpio_configure(PIN_Y,        flags);
    gpio_configure(PIN_SETTINGS, flags);
}

/* ── GB machine (static: avoids stack overflow) ──────────────────────── */
static GB gb;

/* ── Black border helper ─────────────────────────────────────────────── */
static void draw_border(void)
{
    display_rect(0,                    0, GB_OFFSET_X,            DISP_H, 0x0000);
    display_rect(GB_OFFSET_X + GB_W,   0, GB_OFFSET_X,            DISP_H, 0x0000);
    display_rect(0,                    0, DISP_W,         GB_OFFSET_Y,    0x0000);
    display_rect(0, GB_OFFSET_Y + GB_H,  DISP_W,         GB_OFFSET_Y,    0x0000);
    display_flush();
}

/* ── Main ────────────────────────────────────────────────────────────── */
int main(void)
{
    printf("AkiraOS GB/GBC Emulator\n");

    init_gpio();
    load_settings();

    display_clear(0x0000);
    display_text_large(46, 100, "GB", 0xFFFF);
    display_text_large(100, 100, "EMULATOR", 0xFFFF);
    display_text(80, 140, "Loading ROM...", 0xFFFF);
    display_flush();

    gb_init(&gb, rom_data, rom_size);

    draw_border();

    int settings_held = 0;
    int frame_count   = 0;

    printf("[GB] Init OK — entering main loop\n");

    while (1) {
        /* ── Read input ─────────────────────────────────────────────── */
        uint8_t btns = 0;
        if (gpio_read(PIN_UP))    btns |= GB_BTN_UP;
        if (gpio_read(PIN_DOWN))  btns |= GB_BTN_DOWN;
        if (gpio_read(PIN_LEFT))  btns |= GB_BTN_LEFT;
        if (gpio_read(PIN_RIGHT)) btns |= GB_BTN_RIGHT;
        if (gpio_read(PIN_A))     btns |= GB_BTN_A;
        if (gpio_read(PIN_B))     btns |= GB_BTN_B;
        if (gpio_read(PIN_X))     btns |= GB_BTN_SELECT;
        if (gpio_read(PIN_Y))     btns |= GB_BTN_START;

        gb_set_buttons(&gb, btns);

        /* ── Pause menu ─────────────────────────────────────────────── */
        int settings_now = gpio_read(PIN_SETTINGS);
        if (settings_now && !settings_held) {
            int choice = show_pause_menu();
            if (choice == MENU_EXIT) {
                app_switch("supervisor");
                return 0;
            }
            if (choice == MENU_RESTART) {
                gb_init(&gb, rom_data, rom_size);
                draw_border();
                frame_count = 0;
                printf("[GB] Restarted\n");
            }
            settings_held = 0;
            continue;
        }
        settings_held = settings_now;

        /* ── Run one GB frame + optional render skip ────────────────── */
        int mod  = FS_MOD[g_frameskip];
        int skip = (frame_count % mod) != 0;
        gb.ppu.skip_render = (uint8_t)skip;
        gb_step_frame(&gb);
        frame_count++;

        /* ── Display ────────────────────────────────────────────────── */
        if (!skip) {
            display_bitmap(GB_OFFSET_X, GB_OFFSET_Y,
                           GB_W, GB_H,
                           gb.fb, GB_FB_BYTES);
            display_flush();
        }
    }

    return 0;
}
