/**
 * @file main.c
 * @brief AkiraOS Game Boy / Game Boy Color emulator — app entry point
 *
 * Reads buttons via the AkiraOS input API, runs the GB/GBC machine, and scales
 * each 160×144 frame up to fill the display (queried at runtime, so it works on
 * any panel — e.g. the 400×240 Sharp on AkiraConsole Prod, not a hardcoded 320).
 *
 * ROM data is supplied by rom_data.c (generated by rom_to_wasm.py):
 *   const uint8_t  rom_data[];
 *   const uint32_t rom_size;
 *
 * Button mapping (logical AkiraConsole buttons — input_get_buttons() already
 * resolves the physical B/X/Y wiring swap):
 *   D-pad        → GB D-pad
 *   A            → GB A
 *   B            → GB B
 *   X            → GB Select
 *   Y            → GB Start
 *   OK / HOME    → Emulator pause menu
 *
 * @license Apache-2.0
 */
#include "akira_api.h"
#include "akira_console.h"
#include "gb.h"

/* ── ROM data (generated by rom_to_wasm.py) ─────────────────────────── */
extern const uint8_t  rom_data[];
extern const uint32_t rom_size;

/* ── OK / HOME button (zephyr,code = 1) — opens the pause menu ────────── */
#define BTN_MENU_MASK  (1U << 1)

/* ── Frameskip ───────────────────────────────────────────────────────── */
static const int FS_MOD[4] = {1, 2, 3, 4};  /* 60 / 30 / 20 / 15 fps */
static int g_frameskip = 1;                  /* default: 30 fps (every other frame) */

/* ── Colours (RGB565) ────────────────────────────────────────────────── */
#define C_BLACK   0x0000u
#define C_WHITE   0xFFFFu
#define C_LGRAY   0xC618u
#define C_DGRAY   0x4208u
#define C_DIM     0x528Au

/* ── UI layout ────────────────────────────────────────────────────────── */
#define ROW_H     26
#define MENU_PAD  10
#define HDR_H     22

/* ── Display geometry (resolved at runtime) ──────────────────────────── */
static int32_t g_dw = 320, g_dh = 240;   /* actual panel size */
static int g_dst_x, g_dst_y;             /* top-left of the scaled GB image */
static int g_dst_w, g_dst_h;             /* size of the scaled GB image */

/* Scan-line scratch for the nearest-neighbour upscaler (max panel width). */
static uint16_t s_line[512];

/* Compute the largest aspect-preserving rectangle that fits the panel. */
static void compute_geometry(void)
{
    display_get_size(&g_dw, &g_dh);
    if (g_dw <= 0 || g_dh <= 0) { g_dw = 320; g_dh = 240; }

    /* Fit 160×144 into g_dw×g_dh, preserving aspect ratio. */
    if ((long)g_dw * GB_H <= (long)g_dh * GB_W) {
        g_dst_w = g_dw;
        g_dst_h = (int)(((long)g_dw * GB_H) / GB_W);
    } else {
        g_dst_h = g_dh;
        g_dst_w = (int)(((long)g_dh * GB_W) / GB_H);
    }
    if (g_dst_w > (int)(sizeof(s_line) / sizeof(s_line[0]))) {
        g_dst_w = (int)(sizeof(s_line) / sizeof(s_line[0]));
    }
    g_dst_x = (g_dw - g_dst_w) / 2;
    g_dst_y = (g_dh - g_dst_h) / 2;
}

/* ── Pause menu ──────────────────────────────────────────────────────── */
#define MENU_RESUME   0
#define MENU_SETTINGS 1
#define MENU_RESTART  2
#define MENU_EXIT     3
#define MENU_COUNT    4

static const char *MENU_LABELS[MENU_COUNT] = {
    "Resume", "Settings...", "Restart", "Exit to Menu"
};

/* ── Tiny string helpers ─────────────────────────────────────────────── */
static int satoi(const char *s)
{
    int v = 0;
    while (*s >= '0' && *s <= '9') v = v * 10 + (*s++ - '0');
    return v;
}
static void sitoa(int v, char *b, int max)
{
    if (v == 0) { b[0]='0'; b[1]='\0'; return; }
    char t[8]; int ti=0, i=0;
    while (v>0 && ti<7) { t[ti++]='0'+v%10; v/=10; }
    while (ti-->0 && i<max-1) b[i++]=t[ti];
    b[i]='\0';
}

/* ── Settings persistence ────────────────────────────────────────────── */
static void load_settings(void)
{
    char buf[8];
    if (settings_get("gb/frameskip", buf, sizeof(buf)) == 0) {
        g_frameskip = satoi(buf);
        if (g_frameskip < 0) g_frameskip = 0;
        if (g_frameskip > 3) g_frameskip = 3;
    }
}
static void save_int(const char *key, int val)
{
    char buf[8];
    sitoa(val, buf, sizeof(buf));
    settings_set(key, buf);
}

/* ── Input ────────────────────────────────────────────────────────────── */
static inline uint32_t read_buttons(void)
{
    return (uint32_t)input_get_buttons();
}

/* ── Draw helpers ─────────────────────────────────────────────────────── */
static void draw_header(int x, int y, int w, const char *title)
{
    display_rect(x, y, w, HDR_H, C_BLACK);
    display_text(x + MENU_PAD, y + 4, title, C_WHITE);
}

static void draw_row(int x, int y, int w,
                     const char *lbl, const char *val, int sel)
{
    uint16_t bg = sel ? C_BLACK : C_WHITE;
    uint16_t fg = sel ? C_WHITE : C_BLACK;
    display_rect(x, y, w, ROW_H, bg);
    display_text(x + MENU_PAD, y + (ROW_H - 8) / 2, lbl, fg);
    if (val && val[0]) {
        int vx = x + w - 60;
        if (vx > x + 80)
            display_text(vx, y + (ROW_H - 8) / 2, val, sel ? C_LGRAY : C_DIM);
    }
    display_hline(x, y + ROW_H - 1, w, C_LGRAY);
}

/* ── Settings sub-menu ────────────────────────────────────────────────── */
static void show_settings_menu(void)
{
    static const char *FS_LABELS[4] = {
        "Off (60fps)", "Half (30fps)", "1/3 (20fps)", "1/4 (15fps)"
    };
    const int OW = 180;
    const int OH = HDR_H + 2 * ROW_H;  /* Frameskip + Back */
    const int OX = (g_dw - OW) / 2, OY = (g_dh - OH) / 2;

    int cur=0, dirty=1;
    uint32_t prev = read_buttons();

    while (1) {
        if (dirty) {
            display_rect(OX-2, OY-2, OW+4, OH+4, C_DGRAY);
            display_rect(OX,   OY,   OW,   OH,   C_WHITE);
            draw_header(OX, OY, OW, "Settings");
            int ry = OY + HDR_H;
            draw_row(OX, ry, OW, "Frame Skip", FS_LABELS[g_frameskip], cur==0); ry += ROW_H;
            draw_row(OX, ry, OW, "Back", "", cur==1);
            display_flush();
            dirty = 0;
        }
        uint32_t b = read_buttons();
        uint32_t just = b & ~prev;
        prev = b;

        if (just & (AKIRA_BTN_UP | AKIRA_BTN_DOWN)) { cur = (cur + 1) % 2; dirty = 1; }
        if (just & (AKIRA_BTN_LEFT | AKIRA_BTN_RIGHT)) {
            if (cur == 0) {
                g_frameskip = (g_frameskip + ((just & AKIRA_BTN_RIGHT) ? 1 : 3)) % 4;
                save_int("gb/frameskip", g_frameskip);
                dirty = 1;
            }
        }
        if (just & AKIRA_BTN_A) {
            if (cur == 0) { g_frameskip = (g_frameskip + 1) % 4; save_int("gb/frameskip", g_frameskip); dirty = 1; }
            else break;
        }
        if (just & AKIRA_BTN_B) break;
        delay(20000);
    }
}

static int show_pause_menu(void)
{
    /* Wait for the menu button to be released before showing the menu. */
    while (read_buttons() & BTN_MENU_MASK) delay(10000);
    delay(40000);

    const int OW = 170;
    const int OH = HDR_H + MENU_COUNT * ROW_H;
    const int OX = (g_dw - OW) / 2, OY = (g_dh - OH) / 2;

    int cur=0, dirty=1;
    uint32_t prev = read_buttons();

    while (1) {
        if (dirty) {
            /* Slide-in effect: draw overlay from left edge */
            for (int x = OX - 20; x <= OX; x += 8) {
                int cx = x < OX ? x : OX;
                display_rect(cx-2, OY-2, OW+4, OH+4, C_DGRAY);
                display_rect(cx,   OY,   OW,   OH,   C_WHITE);
                draw_header(cx, OY, OW, "PAUSED");
                int ry = OY + HDR_H;
                for (int i = 0; i < MENU_COUNT; i++) {
                    draw_row(cx, ry, OW, MENU_LABELS[i], "", i==cur);
                    ry += ROW_H;
                }
                display_flush();
                delay(8000);
            }
            dirty = 0;
        }
        uint32_t b = read_buttons();
        uint32_t just = b & ~prev;
        prev = b;

        if (just & BTN_MENU_MASK) return MENU_RESUME;
        if (just & AKIRA_BTN_UP)   { cur = (cur + MENU_COUNT - 1) % MENU_COUNT; dirty = 1; }
        if (just & AKIRA_BTN_DOWN) { cur = (cur + 1) % MENU_COUNT;             dirty = 1; }
        if (just & AKIRA_BTN_A) {
            if (cur == MENU_SETTINGS) { show_settings_menu(); dirty = 1; continue; }
            return cur;
        }
        if (just & AKIRA_BTN_B) return MENU_RESUME;
        delay(16667);
    }
}

/* ── GB machine (static: avoids stack overflow) ──────────────────────── */
static GB gb;

/* ── Clear the letterbox border around the scaled image (once) ────────── */
static void draw_border(void)
{
    display_clear(C_BLACK);
    display_flush();
}

/* ── Scale the 160×144 GB framebuffer up to g_dst_w×g_dst_h ───────────── */
/* Nearest-neighbour upscale, one destination row at a time through the OS
 * framebuffer (display_bitmap + a single flush) — the same proven path the
 * emulator used before, which the Sharp panel converts to 1-bit correctly. */
static void render_frame(void)
{
    for (int dy = 0; dy < g_dst_h; dy++) {
        int sy = (dy * GB_H) / g_dst_h;
        const uint16_t *srow = gb.fb + sy * GB_W;
        for (int dx = 0; dx < g_dst_w; dx++) {
            int sx = (dx * GB_W) / g_dst_w;
            s_line[dx] = srow[sx];
        }
        display_bitmap(g_dst_x, g_dst_y + dy, g_dst_w, 1,
                       s_line, (uint32_t)g_dst_w * 2);
    }
    display_flush();
}

/* ── Main ────────────────────────────────────────────────────────────── */
int main(void)
{
    printf("AkiraOS GB/GBC Emulator\n");

    load_settings();
    compute_geometry();

    display_clear(C_BLACK);
    display_text_large(46, 100, "GB", C_WHITE);
    display_text_large(100, 100, "EMULATOR", C_WHITE);
    display_text(80, 140, "Loading ROM...", C_WHITE);
    display_flush();

    gb_init(&gb, rom_data, rom_size);

    draw_border();

    int settings_held = 0;
    int frame_count   = 0;

    printf("[GB] Init OK — entering main loop (panel %dx%d, image %dx%d)\n",
           (int)g_dw, (int)g_dh, g_dst_w, g_dst_h);

    while (1) {
        /* ── Read input ─────────────────────────────────────────────── */
        uint32_t held = read_buttons();
        uint8_t btns = 0;
        if (held & AKIRA_BTN_UP)    btns |= GB_BTN_UP;
        if (held & AKIRA_BTN_DOWN)  btns |= GB_BTN_DOWN;
        if (held & AKIRA_BTN_LEFT)  btns |= GB_BTN_LEFT;
        if (held & AKIRA_BTN_RIGHT) btns |= GB_BTN_RIGHT;
        if (held & AKIRA_BTN_A)     btns |= GB_BTN_A;
        if (held & AKIRA_BTN_B)     btns |= GB_BTN_B;
        if (held & AKIRA_BTN_X)     btns |= GB_BTN_SELECT;
        if (held & AKIRA_BTN_Y)     btns |= GB_BTN_START;

        gb_set_buttons(&gb, btns);

        /* ── Pause menu (OK / HOME) ─────────────────────────────────── */
        int settings_now = (held & BTN_MENU_MASK) ? 1 : 0;
        if (settings_now && !settings_held) {
            int choice = show_pause_menu();
            if (choice == MENU_EXIT) {
                app_switch("supervisor");
                return 0;
            }
            if (choice == MENU_RESTART) {
                gb_init(&gb, rom_data, rom_size);
                frame_count = 0;
                printf("[GB] Restarted\n");
            }
            draw_border();
            settings_held = 0;
            continue;
        }
        settings_held = settings_now;

        /* ── Run one GB frame + optional render skip ────────────────── */
        int mod  = FS_MOD[g_frameskip];
        int skip = (frame_count % mod) != 0;
        gb.ppu.skip_render = (uint8_t)skip;
        gb_step_frame(&gb);
        frame_count++;

        /* ── Display ────────────────────────────────────────────────── */
        if (!skip) {
            render_frame();
        }
    }

    return 0;
}
